### ISSUE TITLE
time in query url is not formatted with UTC timezone

### ISSUE THREAD

**Issue by alexhuang091** [AtlasOfLivingAustralia/alerts#118]
This issue is found when testing alerts with pipeline biocache-service

Steps to reproduce:

1. create an user assertion at Australian local time 10:44 AM. 
2. check https://biocache-test.ala.org.au/ws/occurrences/49d81401-21a6-42df-8fdf-7b5db9c90e38/assertions shows "created": "`2021-06-03T00:44:11Z`", which is correct UTC time. so far so good.
3. do an hourly check at alerts for new annotation, url being `https://biocache-test.ala.org.au/ws/occurrences/search?fq=user_assertions:*&q=last_assertion_date:[2021-06-03T09:51:06Z TO *]&sort=last_assertion_date&dir=desc&pageSize=20&facets=basis_of_record` see this q=last_assertion_date:`[2021-06-03T09:51:06Z TO *] `this is local time zone formatted date, and this query returns no record
4. updated the code to
```
            SimpleDateFormat sdf = new SimpleDateFormat(query.dateFormat)
            sdf.setTimeZone(TimeZone.getTimeZone("UTC")); // this is the new line added
            def dateValue = sdf.format(dateToUse)
```
5. run hourly query again, this time url being `https://biocache-test.ala.org.au/ws/occurrences/search?fq=user_assertions:*&q=last_assertion_date:[2021-06-02T23:54:19Z TO *]&sort=last_assertion_date&dir=desc&pageSize=20&facets=basis_of_record`, this time `q=last_assertion_date:[2021-06-02T23:54:19Z TO *] ` and correct result is returned.

I haven't checked how it works in prod biocaceh-service, but considering the date string in solr is formatted to UTC timezone, using local time zone generated query should have a problem.

**Comment by alexhuang091** [comment]
Nick has a 'new record` alert on prod never triggered since 1st Jun. It https://alerts.ala.org.au/query/show/1066 could be related to this.

On 8th Jun some data were loaded but there was no alert email.

The daily check runs at 8:30 AEST, so without timezone, the start time in fq will be 2021-06-07T08:30:00Z, so the whole fq [2021-06-07T08:30:00Z TO *] effectively is [2021-06-07T08:30:00Z TO 2021-06-07T22:30:00Z]


so from Jun 7 to Jun 9

Nick has a 'new record` alert on prod never triggered since 1st Jun. It https://alerts.ala.org.au/query/show/1066 could be related to this.

On 8th Jun some data were loaded but there was no alert email.

The daily check runs at 8:30 AEST, so without timezone, the start time in fq will be 2021-06-07T08:30:00Z, so the whole fq [2021-06-07T08:30:00Z TO *] effectively is [2021-06-07T08:30:00Z TO 2021-06-07T22:30:00Z]


6.8 8:30

so these 3 queries effectively ran from Jun 7 to Jun 9, 2 of them still can find some records so alert should have been sent.

```
https://biocache-ws.ala.org.au/ws/occurrences/search?q=data_resource_uid:dr1411&fq=first_loaded_date:[2021-06-08T08:30:00Z TO 2021-06-08T22:30:00Z]&sort=first_loaded_date&dir=desc
https://biocache-ws.ala.org.au/ws/occurrences/search?q=data_resource_uid:dr1411&fq=first_loaded_date:[2021-06-07T08:30:00Z TO 2021-06-07T22:30:00Z]&sort=first_loaded_date&dir=desc
https://biocache-ws.ala.org.au/ws/occurrences/search?q=data_resource_uid:dr1411&fq=first_loaded_date:[2021-06-06T08:30:00Z TO 2021-06-06T22:30:00Z]&sort=first_loaded_date&dir=desc
```

**Comment by nickdos** [comment]
I can confirm I've not received email alerts for biosecurity alerts when my setting is `daily` that have gone through to Erin who had `weekly` set. This is a critical bug that needs fixing ASAP.

CC @sat01a

**Comment by Rita-C** [comment]
2:42pm New lists https://lists-test.ala.org.au/speciesListItem/list/dr18506, alerts-test daily notification on lists.

**Comment by nickdos** [comment]
Not sure what you meant there @Rita-C - you did get emails for that list?

**Comment by Rita-C** [comment]
Hi @nickdos , that's a note to myself to check tomorrow.

**Comment by Rita-C** [comment]
@nickdos , code already updated on 12/7/2021 by Alex, and is in prod
https://github.com/AtlasOfLivingAustralia/alerts/blob/master/grails-app/services/au/org/ala/alerts/NotificationService.groovy#L150

**Comment by nickdos** [comment]
I don't think it is working 100%. Erin and I have the same biosecurity alerts set in prod but I had `daily` and she had `weekly` set. I never got any emails and she got an email at end of week with 7 records in it. This was last week at: Monday, 16 May 2022 10:31 AM.

**Comment by Rita-C** [comment]
Yes, I also received biosecurity alerts from prod as I have `weekly`. However, given the code change required by **this** ticket is already in prod, could I suggest we open a new issue to address biosecurity alerts weekly not working?

**Comment by Rita-C** [comment]
#156 raised to investigate biosecurity alerts.
