### ISSUE TITLE
fix unsubscribe logic

### ISSUE THREAD

**Issue by alexhuang091** [AtlasOfLivingAustralia/alerts#126]
Currently when user unsubscribes and there's an account logged in, we require them to be of the same account.

Actually as long as the unsubscribe UUID is correct, we should always allow the user to unsubscribe, not matter which account is logged in or if there's an account logged in.

**Comment by Rita-C** [comment]
Tested on `alerts-test.ala.org.au`

Steps:
_Use species lists alert as the test case_
1. login as user A, make sure species list alert in on
2. logout, and login as user B
3. Find a species list alert email for user A, click "unsubscribe" link from the email
4. Unsubscribe page displayed (even if logged in as user B)

**Comment by Rita-C** [comment]
Not sure the meaning of "Actually as long as the unsubscribe UUID is correct, we should always allow the user to unsubscribe, not matter which account is logged in or if there's an account logged in." @nickdos any ideas?

**Comment by nickdos** [comment]
@Rita-C that refers to the fact that it previously required the user to login before completing the unsubscribe process. This goes against anti-spam laws, as it is a barrier to unsubscribing (people often forget login details or can't access the old email address any longer). 

So now, the unsubscribe action should go through without requiring the user to login.

**Comment by Rita-C** [comment]
Thanks @nickdos 
Tested that the use does not require login to unsubscribe.
