### ISSUE TITLE
Add feature to allow users to unsubscribe via email link

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/alerts#13]
This has been requested before - user no longer visits the ALA and has forgotten their password and just wants to unsubscribe from alerts / blog updates.

We need to provide a link in footer or alert emails, the lets user unsubscribe from all or just that alert.

**Comment by nickdos** [comment]
I think this should be fairly straight forward - generate a hash uuid that is stored in DB along with a command, equivialent to the  user turning off a particular alert type. When user clicks the link, the hash is checked and that command is run for the user (without the user being logged in).

**Comment by m-r-c** [comment]
I have added two lines to the emails:
```
To stop receiving alerts for [query type], click here.
To stop receiving all Atlas of Living Australia alerts, click here.
```

These links will take the user to an Unsubscribe page with the option to disable the specific alert type (first link) or all alerts (second link - all alerts will be listed). The user does not need to log in - a token will be stored against the user (for the unsubscribe all option) and against each individual notification (for the individual unsubscribe option).

The risk is that some could brute-force and unsubscribe other users, but there isn't much we can do about that, short of having the unsubscribe option send a confirmation email to the user. New tokens are created for individual notifications, and the user-level token is recreated every time the user is updated. Far from perfect, but may mitigate the risk a bit.

The following sql will need to be run against the prod database after the next deployment for this to work:
```
update notification set unsubscribe_token = UUID();
update user set unsubscribe_token = UUID();
```

**Comment by m-r-c** [comment]
https://upsource.ala.org.au/alerts/review/ALRTS-CR-1
