### ISSUE TITLE
BS template: include user annotations (biosecurity type) in record details

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/alerts#134]
If possible, include a row for each record that shows one or more user annotations of type "biosecurity". This might be harder to implement, as it will require a second set of lookups against the assertions service for each record (in batches?).

E.g. something like:

| . | . |
|-----|-----|
| Scientific name | Varanus rosenbergi |
| Date of observation | 2012-11 | 
| Biosecurity annotation | Was observed in 2020 but eradication was conducted in early 2021 and no further observations have been recorded since. Date: 2021-06-02 |
| Locality of observation | South Australia |
etc..

**Comment by alexhuang091** [comment]
Hi Nick, is there any `biosecurity` type of issue?

<img width="587" alt="截屏2021-11-05 上午10 24 53" src="https://user-images.githubusercontent.com/61677987/140433826-a131b00d-a066-49da-8029-9c9ff55a4620.png">

**Comment by nickdos** [comment]
I thought there was (told there was I thought). Maybe its the "other" category - I'll check and get back with an answer.

**Comment by nickdos** [comment]
Looks like we need to add that option, so I'll create an issue for it in biocache-service or hubs.

**Comment by alexhuang091** [comment]
> Looks like we need to add that option, so I'll create an issue for it in biocache-service or hubs.

I'll do it.

**Comment by nickdos** [comment]
> > Looks like we need to add that option, so I'll create an issue for it in biocache-service or hubs.
> 
> I'll do it. I mean the code change

Thanks - just reference this issue for the commit/PR. 

I think it just needs an entry in  https://github.com/AtlasOfLivingAustralia/biocache-service/blob/develop/src/main/java/au/org/ala/biocache/dto/AssertionCodes.java
