### ISSUE TITLE
Admin interface to inactivate a user's alerts

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/alerts#14]
We have many orphaned user accounts (dead) that have active alerts that end up bouncing. The admin interface needs a widget to delete all alerts for a given userId. 

Also, It would be good to extend this to be able to inactivate a user account (activated=false) and then this app (and others) to check for this flag and remove all alerts for that user. Maybe another admin button.

**Comment by nickdos** [comment]
users to unsubsubscribe:
ineden@adam.com.au

**Comment by m-r-c** [comment]
Provided by #17
