### ISSUE TITLE
BS template: minor changes

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/alerts#140]
- [x] Update banner image to use version attached to this issue and adjust the  sizing so the image is shown full-size (one to one pixel ratio)
- [x] Sub header be:  New invasive species record**s** – add (s) -  just to be clear that there might be one but often there will be a list of many?
- [x] For the text header: Email alert from **the** Atlas of Living Australia (ALA)
- [x] In the footer: "This email has been generated as part of ALA's national biosecurity alert system. To find out more about this program, read [ALA helps to stop pests in their tracks](https://www.ala.org.au/blogs-news/ala-helps-to-stop-pests-in-their-tracks/) or email support@ala.org.au"   -  I don’t think it’s good practice to write ‘click here’ anymore

Banner image:

![biosecurity-banner_v2](https://user-images.githubusercontent.com/532845/141387076-b26e83a7-dca1-4fc0-9aeb-a67740cfabeb.png)

**Comment by nickdos** [comment]
![image](https://user-images.githubusercontent.com/532845/141601434-9465c617-00b6-4d59-96ce-1f8190bbe45e.png)

![image](https://user-images.githubusercontent.com/532845/141601452-35505ae3-c17e-408a-a21b-cc282d012b2f.png)

**Comment by Rita-C** [comment]
Received an alert email from test, checked it against the four tasks, 
3. the text is "Email alert from the Atlas of Living Australia" - **the** added, however, it does not have **(ALA)**

**Comment by nickdos** [comment]
OK thanks @Rita-C , I'll fix that.
