### ISSUE TITLE
locale issue

### ISSUE THREAD

**Issue by alexhuang091** [AtlasOfLivingAustralia/alerts#146]
In alerts there are lots places use code like this

https://github.com/AtlasOfLivingAustralia/alerts/blob/233c84a26900a22fe8d2da51f2a86e1001ac01ed/grails-app/services/au/org/ala/alerts/UserService.groovy#L146-L148

It uses sitelocal to get i18n code, but acutally it should use the client locale. 

One solution is to use the `LocaleContextHolder.getLocale()` which reads client locale.

**Comment by adam-collins** [comment]
Check everywhere.
