### ISSUE TITLE
Fix i18n code in email text

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/alerts#148]
On alerts-test.ala.org.au, it is sending "New datasets" emails with `{1}` in the body text. which should be substituted for i18n args.

![image](https://user-images.githubusercontent.com/532845/155930335-79ffc5db-a2fe-4d27-ad76-41d30dd67118.png)

I'm not sure what is supposed to be inserted inside the braces, `ALA` possibly(?). I'm guessing it is reading a config var for `org_short_name` or similar.

**Comment by nickdos** [comment]
Check all files in https://github.com/AtlasOfLivingAustralia/alerts/tree/develop/grails-app/views/email that they have:

```gsp
<g:message code="alert.title" args="[grailsApplication.config.getProperty('skin.orgNameLong'), grailsApplication.config.getProperty('skin.orgNameShort')]"/>
```

**Comment by Rita-C** [comment]
likely caused by code change in https://github.com/AtlasOfLivingAustralia/alerts/issues/140

**Comment by Rita-C** [comment]
deployed to test

**Comment by nickdos** [comment]
Code reviewed ✅

**Comment by Rita-C** [comment]
Emails received, email title displayed correctly.
