### ISSUE TITLE
New occurrence datasets email title contains placeholder text

### ISSUE THREAD

**Issue by Rita-C** [AtlasOfLivingAustralia/alerts#149]
Title should not contain {0}, see screenshot:
========

![Screen Shot 2022-03-08 at 1 50 56 pm](https://user-images.githubusercontent.com/29115246/157157040-9bc53dbe-bc94-482c-9f66-e67a9f2012c2.png)

**Comment by Rita-C** [comment]
@nickdos , can you code review please?

**Comment by nickdos** [comment]
Code LGTM ✅
