### ISSUE TITLE
Grails4 and OIDC integration

### ISSUE THREAD

**Issue by yasima-csiro** [AtlasOfLivingAustralia/alerts#153]
This task has following items:

- Grails 4 migration
- Dev CAS - ClientId and Client secret key for OpenConnect integration - https://auth-dev.ala.org.au/cas-management/management/registry/oauth
- Migration of current auth plugin version - 3.2.3 replace by ala-ws-security-plugin-5.0.0-SNAPSHOT
- Add OpenID connect authentication and JWT support
- Create OpenAPI definitions for the APIs
- Upload the API list to the test AWS API Gateway service.

**Comment by yasima-csiro** [comment]
Branch - https://github.com/AtlasOfLivingAustralia/alerts/tree/feature_oidcIntegration

https://github.com/AtlasOfLivingAustralia/alerts/commit/4c34d2c97cfb2f8d9cd3b771fc8601281947696e
https://github.com/AtlasOfLivingAustralia/alerts/commit/2ff430aaea7c4554dbf4339a0f2c072bc6609c58

**Comment by yasima-csiro** [comment]
Ready to hand over to the team.

**Comment by Rita-C** [comment]
OIDC integration test notes:
"APIs which are protected with RequireAPIKey cannot access publicly." - ` https://alerts-test.ala.org.au/api/alerts/user/xxxx` grails error without apikey, should be 403

"Using legacy API key (When FallbackToLegacyBehaviour is true)/Protected Apis can be successfully invoked with legacy API key" - failed

**Comment by sughics** [comment]
Changes now in prod 2.0.1
