### ISSUE TITLE
Admin function - changing alert frequency for another user fails

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/alerts#155]
Using the admin function to edit another users' settings - via https://alerts.ala.org.au/admin/user - allows an admin user to edit the alerts setting for that user.

When I tried to change the frequency from "daily" to "weekly" for a number of different users, it always failed with a message:

`There was a problem updating your alert frequency. Please try again later.`

Investigate why this is not working as intended.

**Comment by kylie-m** [comment]
This appears to be working now
