### ISSUE TITLE
blog emails incorrectly sending daily and weekly

### ISSUE THREAD

**Issue by matthewandrews** [AtlasOfLivingAustralia/alerts#160]
Blog emails are being sent out each day (and each week) even though there is no new blog post.

ALA Blog emails (id 48) are incorrectly being sent for daily and weekly queues (not hourly).

Example: currently the production JSON for recent posts has the latest post on 27 April (last Fri); it's now Tuesday and the same alert was sent in each daily queue.  

Looking at the debug for this alert in admin, it shows "Would send an email: true" for the daily and weekly checks - should be false.

**Comment by timhicks-ala** [comment]
Reported in https://support.ehelp.edu.au/a/tickets/149545 - will keep an eye out for others

**Comment by matthewandrews** [comment]
Another support ticket on this: https://support.ehelp.edu.au/a/tickets/149674

**Comment by sughics** [comment]
Note: The issue described above is not limited to "Blog and News" alerts. Its seems to occur for all alert whose queries do not support filtering by date i.e. 
 - Blog and News
 - Datasets 
 - Species lists
 - Spatial layers
 -  New occurrence datasets

**Comment by sughics** [comment]
Closing this as the issues are mentioned and addressed in #161
