### ISSUE TITLE
Alert spam and realted issues

### ISSUE THREAD

**Issue by sughics** [AtlasOfLivingAustralia/alerts#161]
Below are the finding and issues identified as a part of investigation into a large number of emails being generated by the application for certain subscription frequencies i.e. daily.

### Issue 1
The [**Bootstrap.Groovy** ](https://github.com/AtlasOfLivingAustralia/alerts/blob/master/grails-app/init/au/org/ala/alerts/BootStrap.groovy)file pre-loads queries and related data into the database for the list of predefined Alert types which will be used to request  JSON for comparison based on alert schedules.   
The queries for services and datasets which allow filtering by date are configured with `fireWhenNotZero` property which detects a change when the requested JSON for a service has a value count of greater than 0. The services and datasets which **do not** support date based filtering are **intended** to be configured with `fireWhenChange` property which detects a change when the total number of records returned do not match the previously stored value.   

The JSON diff check on the actual content is only used to detect  changes in cases when **BOTH** the  `fireWhenNotZero` and `fireWhenChange` are false or absent for a given alert. E.g. custom alerts?

In our codebase, the `fireWhenChange` is **not** [set](https://github.com/AtlasOfLivingAustralia/alerts/blob/b983f74ba7201e7d2ea9efadfe5d061ca56e7627/grails-app/init/au/org/ala/alerts/BootStrap.groovy#L174) correctly. It is set as `fireWhenChanged`  and since no such property by that name exists in the relevant class i.e. [PropertyPath](https://github.com/AtlasOfLivingAustralia/alerts/blob/b983f74ba7201e7d2ea9efadfe5d061ca56e7627/grails-app/domain/au/org/ala/alerts/PropertyPath.groovy#L8), the saved value of `fireWhenChange` is always set to `false`.  This is causing the application to go down the wrong execution path during scheduled alert checks i.e. it is doing a JSON diff check to determine a change when it actually only supposed to compare the total number of records.  

This is one potential cause of the alert spam since all the email spams  only occur for Alerts which have the `fireWhenChange` property configured incorrectly. 

Although this value is editable in the UI by an admin, this functionality does not seems to be used often. 

### Issue 2

Further to the issue mentioned above, if the `fireWhenChange`  is configured properly for relevant alerts, the application includes the entire list from a JSON response in the alert email when a change is detected instead of just the new changes. This [functionality](https://github.com/AtlasOfLivingAustralia/alerts/blob/b983f74ba7201e7d2ea9efadfe5d061ca56e7627/grails-app/services/au/org/ala/alerts/EmailService.groovy#L26) will need to be updated to just include the new changes in the email. 

### Issue 3 - Now a seperate issue #163 

Upon closer inspection of the production database (and the admin UI for the application), the saved result of queries for certain alerts (Blogs, Species lists, datasets, Spatial layers and New occurrence datasets )for `daily` frequencies show that they have not been checked or updated recently. Last update was at end the of May 2022 . These are the alerts which have been detecting changes and sending emails on daily basis. 

This **SHOULD NOT** be the case as alert emails can't be triggered without the relevant queries being checked and the results compared for change.  

It is still a mystery as to why and how this occurring. 

One potential explanation for the spam emails is that that the latest query results for the above alert types for `daily` frequency are being compared with the relevant content in the DB i.e. from end of May 2022 and as such change is being detected. The database is then not being updated (for unknown reasons )with the latest change - repeating the cycle of change detection at the next schedule. 

> **_NOTE:_**  I've omitted results of the database on this GitHub issue. Please contact me if you'd like to take a look)

### Issue 4 

Some values configured as Property paths for some Alert queries are no longer valid.
 
- The jsonPath value [layerList](https://github.com/AtlasOfLivingAustralia/alerts/blob/b983f74ba7201e7d2ea9efadfe5d061ca56e7627/grails-app/init/au/org/ala/alerts/BootStrap.groovy#L174) for Spatial layers is no longer valid as the service now return a list at the root level of the JSON.

- The jsonPath value [posts](https://github.com/AtlasOfLivingAustralia/alerts/blob/b983f74ba7201e7d2ea9efadfe5d061ca56e7627/grails-app/init/au/org/ala/alerts/BootStrap.groovy#L254) for Blogs  and News is no longer valid as the service now return a list at the root level of the JSON.

### Issue 5
It would be helpful for debugging to have the prod instance persist `DEBUG` or at-least `INFO` logs - even if it's for a short amount of time. Currently the application is only configured to log at the `WARN` level and as such it is not really possible to debug the application. 

### Issue 6 
The [compareProperties](https://github.com/AtlasOfLivingAustralia/alerts/blob/b983f74ba7201e7d2ea9efadfe5d061ca56e7627/grails-app/services/au/org/ala/alerts/NotificationService.groovy#L246) function used during query debug uses  actual value of the JSON results instead  of the value at the specified property paths for the given query result- this results in inconsistencies between change detections on scheduled alerts and admin triggered debugging of an alert. 

### Issue 7
Integration tests need to updated to account for the current list of default alerts and properties. Test cases also need to account for new changes and daily frequencies.

**Comment by sat01a** [comment]
@adam-collins is assisting @sughics on issue 2 and 3

**Comment by sughics** [comment]
Issues 1, 2, 4, 6 have been addressed in the relevant branch [issue-161 ](https://github.com/AtlasOfLivingAustralia/alerts/tree/issue-161). 

Pending findings from investigations into issue 3.

**Comment by sughics** [comment]
Issues 7 has been addressed.

**Comment by peggynewman** [comment]
@sughics and @adam-collins -2 things that might be related to Issue #3 - 
1. I keep getting alerts for "New occurrence datasets" for empty biocollect data resources with no data in them, thus a bit misleading
2. @patkyn and I have been looking at the collectory data resource dates 'last checked' and 'data currency' (I think) - are they used by alerts at all?

**Comment by sughics** [comment]
@peggynewman . 

1.  "New occurrence datasets" is one of the [alerts](https://github.com/AtlasOfLivingAustralia/alerts/issues/160#issuecomment-1169389886) affected by issue 3  mentioned above. I'm subscribed to daily frequency for it receive the following email  every morning. 

![Screen Shot 2022-07-04 at 1 28 09 pm](https://user-images.githubusercontent.com/105408469/177076491-4783325e-728f-473f-97cc-e3c2a612b8d5.png)

**Comment by peggynewman** [comment]
@sughics for (1) these are full of duplicates and empty datasets, and it looks quite bad I think. Should I raise an issue for that on this repo?

**Comment by sughics** [comment]
> @sughics for (1) these are full of duplicates and empty datasets, and it looks quite bad I think. Should I raise an issue for that on this repo?

Re the duplicates and empty datasets -  The apparent duplicates in the email above are coming from the collectry itself.  In the email above, all the apparent duplicate records have unique `uid`.  The  data resource `uid` on  [resources](https://collections.ala.org.au/ws/dataResource?resourceType=records) returned by collectory is used to generate the diff for alert email. 

Are these records technically valid in Collectory?  i.e. Exact same name, descriptions with different resource id and different metadata update dates, empty datasets etc.?

Alerts just generates a simple diff based on a comparison using a configured JSON key on the returned dataset and doesn't really do further checks on actual records themselves e.g. for empty datasets, whether the resource is reachable. 
In case of an actual  duplication on a `uid`,  Alerts does not have an explicit check for duplication so it probably won't behave as expected.  

If we want to do duplication checks and further checks on the data resource itself within alerts, I would recommend raising an issue.  I would classify that as more of an enhancement to the application though.

**Comment by sughics** [comment]
@adam-collins . Please find https://github.com/AtlasOfLivingAustralia/alerts/issues/163  for database issues

**Comment by peggynewman** [comment]
Hi Sushant, you're right these are technically valid in Collectory, and I see now that the resources query is `https://collections.ala.org.au/ws/dataResource?resourceType=records` which is a default setting when a new data resource is created. I might try and get that default setting switched off in the Collectory.

**Comment by sughics** [comment]
Changes now in prod 2.0.1
