### ISSUE TITLE
Alerts requests a client credentials access token for each user in the database twice per day

### ISSUE THREAD

**Issue by sbearcsiro** [AtlasOfLivingAustralia/alerts#174]
@joe-lipson did a deep dive on some auth server issues and found that the alerts server was requesting a new client credentials access token for each user in the database twice per day, causing excess load on the auth server: https://confluence.csiro.au/display/~lip042/Mongo+CPU+spikes

There are a few options for mitigation here:
1. Move the user update job outside peak / work day hours (it's currently running at 8:30am and 4:30pm)
2. Update the user update job to use batch userdetails lookups
3. Update the ala-ws-plugin to cache client credentials tokens.

3 is currently being addressed in https://github.com/AtlasOfLivingAustralia/ala-ws-plugin/pull/10

**Comment by sughics** [comment]
Release with 2.0.3
