### ISSUE TITLE
Multiple emails sent for Blogs and News alert without blog being published

### ISSUE THREAD

**Issue by kylie-m** [AtlasOfLivingAustralia/alerts#183]
This issue was reported by an ALA user.
It applies to **weekly** email alerts for **Blogs and News**. 

User noticed the last 3 email alerts were the same and almost look like spam. This was despite no new blogs being published since August.

Note, this doesn't seem to be affecting daily alerts from Blogs and News, as I have this activated for one of my ALA accounts (gmail) and have not received any strange/additional emails. 

I have been unable to replicate the issue yet, but have activated weekly alerts for my other ALA account (csiro) to test this. 

Relates to ticket https://support.ehelp.edu.au/a/tickets/185336

@adam-collins

**Comment by kylie-m** [comment]
Following up on this, I just received the weekly blog alert email (1:11pm AEST). The last blog it shows was from August.

There was a new blog published earlier this morning (10.45am), but it is not listed in the email, so the email content appears outdated, only showing the latest ALA blogs from August and earlier. Unsure if this is some sort of cutoff time, or a second issue.

 
![Screen Shot 2023-09-26 at 1 34 00 pm](https://github.com/AtlasOfLivingAustralia/alerts/assets/90439797/a5c4db02-4e8f-400b-ba1b-b69ff3003749)

**Comment by timhicks-ala** [comment]
Further reported in https://support.ehelp.edu.au/a/tickets/192570

**Comment by kylie-m** [comment]
I received the same again today, screenshot below. FYI the latest blog there, ALA's International Biodiversity Engagements, was published back on 14 Nov 2023. 

![Screenshot 2024-01-10 at 9 51 47 am](https://github.com/AtlasOfLivingAustralia/alerts/assets/90439797/8497f25d-c933-4f0a-a0e4-2194097e8558)

**Comment by adam-collins** [comment]
The database transaction was being reset before the scheduled task WeeklyQueriesJob was completed. This resulted in irregular behaviour such as the database not updating. This made it look like there were always new Blogs and News alerts. This is fixed in the commit https://github.com/AtlasOfLivingAustralia/alerts/commit/5eb37ba20867afa8f001ebcdaf4ae7cf3cc7a8f6, and also ala-install pull request https://github.com/AtlasOfLivingAustralia/ala-install/pull/768.

No duplicate Blogs and New alert emails are expected from February. They will still be sent next week.

**Comment by kylie-m** [comment]
This is great news - thanks Adam!

**Comment by kylie-m** [comment]
An additional user has reported this issue, receiving emails on 8th and 15th April. For context, no new blogs have been published on ALA production since 22 March. This user is subscribed to weekly blog alerts. 

![Screenshot 2024-04-22 at 1 39 37 pm](https://github.com/AtlasOfLivingAustralia/alerts/assets/90439797/4770fb76-31ca-48e4-8b99-56e4970c7d8d)


- Reported directly via email, I'm happy to forward as needed

**Comment by adam-collins** [comment]
new problem exists in a new issue
