### ISSUE TITLE
Refresh ALA blog alerts email template

### ISSUE THREAD

**Issue by kylie-m** [AtlasOfLivingAustralia/alerts#189]

**Comment by kylie-m** [comment]
refreshed v1 design done; Bai implementing

**Comment by qifeng-bai** [comment]
And this moment, Image of the blog is not able to be displayed

**Comment by kylie-m** [comment]
- remove images
- remove dashes in date subheading (29-May-2024 to 29 May 2024)
- investigate and remove question marks in text

**Comment by kylie-m** [comment]
Alerts are looking good across desktop and mobile, gmail, yahoo and Outlook, and light/dark mode.

A minor issue on dark mode in Gmail:
the text in the header banner also turns dark, and there isn't sufficient contrast against the dark blue banner, so it fails WCAG AAA and AA for all text sizes. (this is same for Biosecurity Alerts, but on Rust orange, it passes AA at least)


![IMG_0814 (1)](https://github.com/AtlasOfLivingAustralia/alerts/assets/90439797/8b34f70c-17b7-4a89-9f9f-de08471eeb6f)

**Comment by kylie-m** [comment]
@qifeng-bai as discussed, to fix the above accessibility issue, can we please: 
- remove the Ocean blue banner
- change header text to ALA Charcoal (#212121)

One more small text change:
- To make the "View more" button more accurate and descriptive, can we update text to  "All ALA news & updates"

**Comment by kylie-m** [comment]
Update is looking great, thanks Bai. Noting here for reference that we agreed to return to the Ocean blue banner (with a slight design update) with white text as the email design didn't work without a banner. We can investigate a fix for the header text in Gmail dark mode in a future release. 

Button text looks great too.

It just looks like the mailing address needs to be re/added - 

![IMG_0915](https://github.com/AtlasOfLivingAustralia/alerts/assets/90439797/f21b7856-132b-40f9-b081-c06ebf538491)
![IMG_0916](https://github.com/AtlasOfLivingAustralia/alerts/assets/90439797/cfd77abf-8127-4b8b-9c76-038435a7be12)
![IMG_0917](https://github.com/AtlasOfLivingAustralia/alerts/assets/90439797/85519625-247b-4e75-a94a-e999d31c7a27)
![IMG_0918](https://github.com/AtlasOfLivingAustralia/alerts/assets/90439797/e12f0cb6-5093-4531-bf3d-343d371e3a94)

**Comment by qifeng-bai** [comment]
@kylie-m Mailing address added

**Comment by kylie-m** [comment]
Looks great to me! Thanks for this @qifeng-bai
