### ISSUE TITLE
Analysis of shapefiles – Biosecurity alerts

### ISSUE THREAD

**Issue by kylie-m** [AtlasOfLivingAustralia/alerts#190]
Analysis of the supplied shapefiles for biosecurity alerts. 

- [x] Files supplied by ALA SDS team.

**Comment by adam-collins** [comment]
coastal_waters
- 2.6MB .shp file. Getting a bit large.  
- 8 features. Needs to have only 1 feature.
- File is in EPSG:4283. ALA uses EPSG:4326.
- Fix the source declaration. A link to a file on cloudfront is insufficient.
- Reason for use is incorrect. e.g.
  - `The existing state layer`. There are several.
  - `is only terrestrial`. There is one with a coastal buffer.

aus_territory
- 460KB .shp file. It is not too large.
- 1 feature.
- File is in EPSG:4283. ALA uses EPSG:4326.
- Fix the source declaration. A link to a file on cloudfront is insufficient.
- The link to the script that modified the source file is wrong.
- There is no modifier script or source for the files used, however I did notice that according to this aus_territory file:
  - IMCRA 4 Regions layer is out of date; Christmas Island Province, Timor Province and Northwest Shelf Transition are now smaller.
  - EEZ layer is out of date for the same reason.
  
Uploaded as-is:
- coastal_waters, q=spatialObject:9230979
- aus_territory, q=spatialObject:9230972

**Comment by adam-collins** [comment]
I am assuming nothing more is required for the analysis
