### ISSUE TITLE
Possible issues in subscribe a biosecurity alert

### ISSUE THREAD

**Issue by qifeng-bai** [AtlasOfLivingAustralia/alerts#196]
Quote from the comment in :https://github.com/AtlasOfLivingAustralia/biocache-service/issues/886

@adam-collins commented:

```
"species_list_uid is only usable for authoritative lists. 
e.g. https://biocache.ala.org.au/occurrences/search?q=species_list_uid:dr947

species_list is what you want for non-authoritative lists.
 e.g. https://biocache.ala.org.au/occurrences/search?q=species_list:dr21646"
```

However, when we create a subscription in line : https://github.com/AtlasOfLivingAustralia/alerts/blob/develop/grails-app/services/au/org/ala/alerts/QueryService.groovy#L298

1, We need to build the query depends on if the list is authoritative or non-authoritative.  [Done]

2, The notification service  lists every species in the list, and iterate each species,  use its KVP to construct a fq, and then send the query to Biocache.  

- Since it uses different way of search records, the records it returns may be different with the results returned from the biocache query on species list id.

3.  **For some large lists, alerts may need to send >10,000 queries to Biocache, which will increase the burden on Biocache and also reduce the performance of alerts.**

Question to @mjwestgate 
We scheduled to check biosecurity updates at 9:30 every Wed, and  we returns records which were loaded  8 days ago or observed 29 ago.

Let us say, if we ran a first check on Last Wed (13/Mar) .  it returned us the records loaded 8 days/observed 29 days, which are ~5 March, and ~ 6 Feb

Now, we are going to run another check on this Wed 20 Mar,  shall we only return records only uploaded /observed after last Wed (13 Mar), since the alerts about those records uploaded/observed before 13 Mar has been sent to the users

**Comment by adam-collins** [comment]
Some history:
- Original biosecurity alerts were created similar to other alerts. This can be seen in `createBioSecurityQuery()`.
- New biosecurity alerts have a different requirement for performing a query. A different function is used.

Some fields in the old biosecurity alert are not used in the new biosecurity alert. This is one example, `occurrences/search?q=species_list_uid:` is never called by the scheduled task. 

It may be called elsewhere and may need removal. 

This is that each item in the species list is now queried separately. Each of these separate queries may make use of additional information in the species list for the list item, e.g. kvpValues. 

A starting point to find the new flow is the usage of `Boolean isBioSecurityQuery(Query query)`

**Comment by qifeng-bai** [comment]
The url in query for biosecurity is used to find the dataResourceId 
https://github.com/AtlasOfLivingAustralia/alerts/blob/develop/grails-app/services/au/org/ala/alerts/NotificationService.groovy#L424

**Comment by mjwestgate** [comment]
Hello Bai! A few dot points re: your question:

- we currently send alerts out weekly - it is Wednesday to give the Data team time to load data Monday/Tuesday - Thursday is permissible too, but emails can’t go out on Friday as some recipients have mandatory reporting that can’t happen in <24 hours, meaning they’d have to work weekends
- The uploaded date should be set to return records since the previous email. The eventDate can be longer. That way we shouldn’t ever email out records twice.

**Comment by qifeng-bai** [comment]
dr22127 is [ACT_Weeds_List] is NON-authoritative list
https://lists-test.ala.org.au/speciesListItem/list/dr22127

Then we should use : species_list in biocache , however, the url: https://biocache-test.ala.org.au/occurrences/search?q=species_list:dr22127 failed.

We need to use authoritative query to get the result:
https://biocache-test.ala.org.au/occurrences/search?q=species_list_uid:dr22127

**Comment by adam-collins** [comment]
dr22127 on test is private. Private lists should never be authoritative. species_list and species_list_uid should not work for private lists because authentication is not built into biocache-service for this.

**Comment by qifeng-bai** [comment]
@adam-collins Can we subscribe a private list?
