### ISSUE TITLE
Biosecurity Alert email -  content enhancements and clarity

### ISSUE THREAD

**Issue by kylie-m** [AtlasOfLivingAustralia/alerts#197]
Content enhancements for biosecurity alert emails

1. There will be a technical limit to the number of records we can show per email. We need to make it extremely clear for users if/when this is the case, as the risks would be very high if a record was to go unnoticed by a subscriber. 

- Systems team (Kylie) to brainstorm 1st iteration content wording and design to communicate this clearly
-    this was briefly discussed at our last standup, suggestions included wording near the top of the email. 

2. The wording around 'flag an issue' needs to be reviewed and updated for clarity and correctness. Essentially, we need to direct users to the original platform, or if the require help, to seek help with us. We cannot assume responsibility to correct the record ourselves as we don't normally do this. 

3. Review general phrasing and semantics - eg. 'alerts' versus 'records'  - align this with admin page wording

**Comment by kylie-m** [comment]
@qifeng-bai the email text is looking great for first version. Only one small edit below, about annotations in the dark orange part of footer.

From: 
"Please either annotate the record in the provider platform itself or notify us at [biosecurity@ala.org.au](mailto:biosecurity@ala.org.au) and **we can make the suggested change**."

to:
"Please either annotate the record in the provider platform itself or notify us at [biosecurity@ala.org.au](mailto:biosecurity@ala.org.au) for assistance."

**Comment by qifeng-bai** [comment]
Done

**Comment by kylie-m** [comment]
Looks good to me, I'd call it complete for this first version
