### ISSUE TITLE
Biosecurity Alerts admin function - page content clarity & function implementation

### ISSUE THREAD

**Issue by kylie-m** [AtlasOfLivingAustralia/alerts#198]
Review content on Biosecurity Alerts admin page, specifically to improve the clarity and consistency. For example, semantics around 'alerts' versus 'subscriptions',  'subscribers', and so on. 

Possible examples:

"Create a new alert"
"Reporting"
 subtitle/para: "Download CSV list of all occurrences from all alerts"
"Manage alerts"
Subtitle, replace there are 22 subscription(s) with "22 active alert(s)"

**Comment by qifeng-bai** [comment]
My understanding is:   We subscribe to a subscription. If new records come into this subscription, we send email/notification/email to the subscribers

**Comment by kylie-m** [comment]
Looking good for v1, UAT to follow
