### ISSUE TITLE
The var of totalRecords are used in a wrong way

### ISSUE THREAD

**Issue by qifeng-bai** [AtlasOfLivingAustralia/alerts#202]
https://github.com/AtlasOfLivingAustralia/alerts/blob/develop/grails-app/services/au/org/ala/alerts/EmailService.groovy#L121

queryService.fireWhenNotZeroProperty(queryResult), it is used to decide if emails should be sent when no records. 

This call only returns the value of 'fireWhenNotZero' , Nothing to do with totalRecords

For example
Property Paths
[name: totalRecords, path: totalRecords, fireWhenNotZero: true, fireWhenChange: false](http://localhost:8000/propertyPath/show/57)
[name: last_loaded_record, path: occurrences[0].uuid, fireWhenNotZero: false, fireWhenChange: false](http://localhost:8000/propertyPath/show/58)

**Comment by qifeng-bai** [comment]
I believe it is not the correct way of using "fireWhenNotZeroProperty". If it causes other bugs after this statement removed, we will fix the bugs

**Comment by adam-collins** [comment]
Closing it as I do not want to touch it if there is not a specific problem.
- I suspect the original purpose of `fireWhenNotZero` is not as important given the wide spread use of a comparison between new and old results.
- I wonder if the field has been repurposed in some places and that is why it can look odd in the code.

**Comment by qifeng-bai** [comment]
I have reviewed  codes related to this fireWhenNotZero.  There is no function to update this property value, and either no methods to update the true/false value of this fireWhenNotZero to a total number of records.

I assure the line of using fireWhenNotZero as totalNumber in emailService is incorrect
