### ISSUE TITLE
Analysing spatial boundaries

### ISSUE THREAD

**Issue by turley85** [AtlasOfLivingAustralia/alerts#205]
[AlertsMilestones.xlsx](https://github.com/AtlasOfLivingAustralia/alerts/files/15145688/AlertsMilestones.xlsx)

Spatial category priority:
1. National, State & Shape
AUS_CEBO - National boundary - https://lists-test.ala.org.au/speciesListItem/list/dr22384
QLD_PlantHealth - State Boundary - https://lists-test.ala.org.au/speciesListItem/list/dr22405
 NSW_NPWS_Hunter_Weeds - Custom (shape file) Boundary -https://lists-test.ala.org.au/speciesListItem/list/dr22392 - https://csiroau.sharepoint.com/:f:/r/sites/Biosecuritycollective-BiosecurityAlerts/Shared%20Documents/Biosecurity%20Alerts/Lists/Shapefiles/shapefiles/NSW_NPWS_Hunter?csf=1&web=1&e=PBwxbm

**Comment by turley85** [comment]
@kylie-m, links to the lists in Test have been updated, and I've linked you to the shapefile in Teams for Hunter list.

**Comment by kylie-m** [comment]
Excellent, thanks Andrew, will do!

**Comment by kylie-m** [comment]
Also need to include LGA in this list and in testing
