### ISSUE TITLE
Unable to delete a specific subscriber

### ISSUE THREAD

**Issue by kylie-m** [AtlasOfLivingAustralia/alerts#206]
On the Biosecurity Alerts Admin page, for most lists we are able to add and remove subscribers easily without any issues. 

For the ACPPO list, we have one subscriber (the only one with an @gmail.com address) registered that we cannot delete. 

Testing notes:
- Other @gmail.com subscribers for ACPPO and other lists can be added and removed successfully
- Other subscribers such as @csiro emails can be added and deleted successfully on all lists
- I have also tried refreshing the page several times, logging out and back in, and using different browsers (Chrome, Firefox, Safari or Edge)

**Comment by qifeng-bai** [comment]
This failure is due to the  creation of duplicate user accounts.
The reason for the duplication of the user account is still unknown.

```
| 124 |       0 | 17ba647e-acec-44db-a7cf-3db236068248                         | 0x00           |            3 | c393dd50-6d9f-40cb-8ea8-bbea167fc276 | azzerger@gmail.com                        |
| 125 |       0 | 17ba647e-acec-44db-a7cf-3db236068248                         | 0x00           |            3 | 7b0412de-cb87-4cd6-b8a3-3ff9c4f97540 | azzerger@gmail.com
```

**Comment by qifeng-bai** [comment]
Able to delete users despite the existence of duplicate user records. However, the cause why the occasional duplication of users is still unidentified

**Comment by kylie-m** [comment]
Confirming I've tested and am now able to add and delete gmail addresses from all 3 alert lists

**Comment by qifeng-bai** [comment]
I will monitor the user table to check any duplications that may occur again.
