### ISSUE TITLE
Biosecurity Alerts email template compatibility with Gmail and others

### ISSUE THREAD

**Issue by kylie-m** [AtlasOfLivingAustralia/alerts#207]
The Biosecurity Alerts email template is working fairly well in Outlook, for desktop and mobile.

For Gmail, Yahoo and Hotmail, the template is not yet compatible.

**Comment by adam-collins** [comment]
Details required.

**Comment by qifeng-bai** [comment]
Here is the issue

![Screenshot 2024-05-03 at 3 40 56 pm](https://github.com/AtlasOfLivingAustralia/alerts/assets/31238531/c6d310bc-99d6-4e3c-9693-d2079ba22eb5)

**Comment by qifeng-bai** [comment]
After CSS updated:

![Screenshot 2024-05-03 at 4 20 37 pm](https://github.com/AtlasOfLivingAustralia/alerts/assets/31238531/9e9ea8d7-3a5d-4b2a-86c8-43220a09f4e3)

**Comment by qifeng-bai** [comment]
An alternative is to give a fixed height and width; it will display as shown below. However, it may distort the image by stretching or compressing its aspect ratio.

![Screenshot 2024-05-06 at 9 17 48 am](https://github.com/AtlasOfLivingAustralia/alerts/assets/31238531/fcd0fcba-056b-4db3-b8a4-b67b84115837)

**Comment by kylie-m** [comment]
Thanks Bai, can we do option 2 with the small gap added

**Comment by kylie-m** [comment]
Gmail formatting on desktop has improved, great work!
<img width="1022" alt="Screenshot 2024-05-08 at 9 36 54 am" src="https://github.com/AtlasOfLivingAustralia/alerts/assets/90439797/48209e37-05e1-4eac-9b25-b04ef07bee2c">

**Comment by kylie-m** [comment]
trying swap of map and image

**Comment by qifeng-bai** [comment]
map and image swapped

**Comment by kylie-m** [comment]
swapped map and image looking good on gmail. Unfortunately some yahoo mail formatting issues, see screenshots:

<img width="1789" alt="Screenshot 2024-05-08 at 5 09 39 pm" src="https://github.com/AtlasOfLivingAustralia/alerts/assets/90439797/fcc3aec7-d99c-4e2b-b4ef-19527d5560a4">
<img width="689" alt="Screenshot 2024-05-08 at 5 09 48 pm" src="https://github.com/AtlasOfLivingAustralia/alerts/assets/90439797/f0ab7d8b-2717-4ace-996e-78dffeede0e3">
