### ISSUE TITLE
Missing images in biosecurity alerts email template

### ISSUE THREAD

**Issue by kylie-m** [AtlasOfLivingAustralia/alerts#208]
For the Biosecurity Alert emails, there are some cases where the occurrence record thumbnail image is missing. 
- Typically, this is when the image is still processing.
- This is distinct from there being no image supplied at all, in which case we display a "no image available" placeholder

Screenshot of issue below:
<img width="630" alt="Screenshot 2024-04-30 at 10 32 52 am" src="https://github.com/AtlasOfLivingAustralia/alerts/assets/90439797/3cdaf74a-7e3a-43d3-bbf5-f52d0439aa02">

- Note the link is still active, clicking on the broken image successfully linked to the occurrence record:
https://biocache.ala.org.au/occurrences/2827a140-2252-4fa8-a918-39955e8bf2dc

To avoid the broken image, can we instead display the "no image available" placeholder in this scenario?

**Comment by qifeng-bai** [comment]
Using CSS, instead of  external JS 'onerror'  method which is most likely forbidden by emails service

**Comment by qifeng-bai** [comment]
After implementing a default image for missing thumbnail,  Gmail prevents showing the pics

![Screenshot 2024-05-03 at 8 58 49 am](https://github.com/AtlasOfLivingAustralia/alerts/assets/31238531/5074ebab-30d8-40dc-9745-4e8e728583b6)

**Comment by adam-collins** [comment]
Underline species name so it is clear it is a link.

Swap Image and Map images so the map is displayed first.

Left align content so it does not centre.

**Comment by qifeng-bai** [comment]
![Screenshot 2024-05-20 at 2 11 41 pm](https://github.com/AtlasOfLivingAustralia/alerts/assets/31238531/2421b2cb-aa62-40ba-8835-a5447a84ee8e)

**Comment by kylie-m** [comment]
the new changes are looking good in Outlook, gmail and yahoo mail on desktop
