### ISSUE TITLE
Biosecurity Admin role creation

### ISSUE THREAD

**Issue by kylie-m** [AtlasOfLivingAustralia/alerts#209]
Currently, the Biosecurity Alerts admin page requires users to be ROLE_ADMIN in order to access and edit.

We require the creation of a new role, for our Biosecurity Admin team members to be able to access and edit the admin page for _Biosecurity_, without needing the additional permissions that ALA ROLE_ADMIN users have.

Role to be called: ROLE_BIOSECURITY_ADMIN

**Comment by kylie-m** [comment]
create in test and prod

**Comment by kylie-m** [comment]
ROLE_BIOSECURITY_ADMIN created in test and prod
@qifeng-bai

**Comment by kylie-m** [comment]
@qifeng-bai I'm unable to view the admin page using an account with this role, could you investigate on your side?

**Comment by yasima-csiro** [comment]
As per the discussion [here](https://github.com/AtlasOfLivingAustralia/userdetails/pull/193), Biosecurity admins should have both roles - ROLE_BIOSECURITY_ADMIN and ROLE_USER_CREATOR to manage biosecurity alerts and create users in userdetails.
