### ISSUE TITLE
Explore Codepipeline deployment pipeline

### ISSUE THREAD

**Issue by adam-collins** [AtlasOfLivingAustralia/alerts#210]
This is an exploration of using CodePipline to 
- build a Docker container of a branch
- publish the container to ECR
- deploy to EKS

Considerations
- automatic and manual deployment
- external configuration

Outputs will include
- branch with all code
- documented process employed, including future recommendations where more work is required or decisions need to be made.

**Comment by hamzajaved-csiro** [comment]
Development Branch:
[https://github.com/AtlasOfLivingAustralia/alerts/pull/204](https://github.com/AtlasOfLivingAustralia/alerts/pull/204)

Code Pipeline for branch:
https://ap-southeast-2.console.aws.amazon.com/codesuite/codepipeline/pipelines/alerts-ci-code-pipeline/view?region=ap-southeast-2

Confluence Doco:
https://confluence.csiro.au/display/ALASD/Developer+Pipeline+-+Alerts

Progress until now;
- Build
- Deploy to EKS
- Store config files in Kube secrets (May need a rethink)

Todo:
- Publish artifacts to Nexus repository
- Make ECR repo public? (Maybe just the master build images?)

Still have to wait for updates to ala-regolith repo to build infrastructure for external access to EKS cluster.
https://github.com/AtlasOfLivingAustralia/ala-regolith

**Comment by adam-collins** [comment]
Provisioning of RDS for the database is working.
