### ISSUE TITLE
alerts-test – deleted user accounts still showing in alerts list

### ISSUE THREAD

**Issue by kylie-m** [AtlasOfLivingAustralia/alerts#214]
As part of testing, I've been creating and deleting accounts for a single gmail address in userdetails (test). It appears that deleted accounts still linger in alerts-test, and I presume emails are sent out to them also (have set daily alerts to test for this overnight). 

When I look in [userdetails-test](https://aws-auth-test-2023.test.ala.org.au/userdetails/admin/user/list), I only have one account showing for that email address:
<img width="1584" alt="Screenshot 2024-05-08 at 4 40 00 pm" src="https://github.com/AtlasOfLivingAustralia/alerts/assets/90439797/b0e57f2e-5cde-4865-8f69-906d1df7c5df">

However, when I search for the user email in [alerts-test](https://alerts-test.ala.org.au/admin/user), these accounts are all listed, - in this case 3 accounts with unique IDs to be expected), but all with the same email address. When I inspect each user's alert subscriptions, they each have active subscriptions.

<img width="1328" alt="Screenshot 2024-05-08 at 4 37 24 pm" src="https://github.com/AtlasOfLivingAustralia/alerts/assets/90439797/9e71a5b9-1489-48e5-a467-524319de7a2b">

**Comment by kylie-m** [comment]
may relate to #213

**Comment by qifeng-bai** [comment]
I suspect the issue was caused by email sync process

**Comment by qifeng-bai** [comment]
> See also #213 - it seems like the alert subscriptions from previous accounts might be carried over to new accounts created under the same email address (assuming the account has first been deleted)

Alerts does not if an account has been deleted.  When  a user subscribe a query, the Alerts only check and add this user's **email** into system. The alerts does not check the user's sequence ID or ALA ID.

So when you delete a user and create a user again in UserDetails,  Alerts will use the new ID which the email is linked to.
