### ISSUE TITLE
Add ALA mailing address to Alert email footer (Blog and Biosecurity)

### ISSUE THREAD

**Issue by kylie-m** [AtlasOfLivingAustralia/alerts#220]
To comply with legal requirements, we need to add a mailing address to our alert emails.

Could we add this info between the two lines of text we currently have? Compressed into two lines is ok to save space:

![Screenshot 2024-06-12 at 10 45 26 am](https://github.com/AtlasOfLivingAustralia/alerts/assets/90439797/82879dfe-aaed-4010-baa8-83e835984b0a)

ie.:

You are receiving this email because you opted in to ALA alerts.

Our mailing address is:
Atlas of Living Australia, GPO Box 1700, Canberra, ACT 2601 Australia

Don't want to receive these emails? You can [unsubscribe](https://alerts-test.ala.org.au/unsubscribe?token=ed7dd049-6f98-49b9-a0b9-6fce5d276afc).

Also for reference, see example in our MailChimp emails:
![Screenshot 2024-06-12 at 9 36 49 am](https://github.com/AtlasOfLivingAustralia/alerts/assets/90439797/ed2a035f-45fa-42c1-a4d3-5f238264a5db)

(for more background info: see the Spam Act 2003 and the Spam Regulations. For more information on these regulations, please refer to this ACMA link: https://www.acma.gov.au/avoid-sending-spam)

**Comment by kylie-m** [comment]
Looks good on biosecurity alerts, thanks @qifeng-bai 
Could we remove the bold and then (when you have time) add the text to blog alerts too?

**Comment by qifeng-bai** [comment]
Added and deployed

**Comment by kylie-m** [comment]
Thanks Bai, the mailing address looks good! I tested on Biosecurity + Blogs, light and dark mode, outlook + gmail,  and desktop + mobile

**Comment by kylie-m** [comment]
The header text still goes dark on dark mode (doesn't contrast with banner) but we can revisit 
![IMG_0814](https://github.com/AtlasOfLivingAustralia/alerts/assets/90439797/3a9848d8-61e6-4c78-91d9-d5f3e31051e5)
