### ISSUE TITLE
Issue adding new alert into prod. alert admin page

### ISSUE THREAD

**Issue by turley85** [AtlasOfLivingAustralia/alerts#234]
I’m trying to add a new list into the alerts admin page. I’ve added the list UID and my email address and clicking “subscribe alert”. It’s then taking be mack to the email subscription page with error “You don’t have permission to view that page!
![image (1)](https://github.com/AtlasOfLivingAustralia/alerts/assets/114458077/2c39ae6c-52f5-4109-92e8-5815e3dede94)
![image (2)](https://github.com/AtlasOfLivingAustralia/alerts/assets/114458077/2c212dc7-1980-4301-96ef-34ac8933a00f)

Could this be resolved so I can add a new alert in prod please?

**Comment by kylie-m** [comment]
Thanks for flagging Andrew, 

Confirming I'm getting the same issue on my ROLE_BIOSECURITY_ADMIN (ie non ALA Admin) testing account. 

Steps to replicate the error were as above, the URL of the page with the error msg is https://alerts.ala.org.au/notification/myAlerts

**Comment by kylie-m** [comment]
@qifeng-bai after further testing on production with my ROLE_BIOSECURITY_ADMIN account found:

Functioning:
 - delete a subscriber, delete an alert
 - preview
 - notify

Not functioning (same result as above)
- download CSV
- search (it will start to show results in the dropdown ok, but once a name is selected, this is where it fails and error is shown)

**Comment by kylie-m** [comment]
Hi @qifeng-bai, thanks for working on this! Most of the access issues seem fixed now.  

Testing on _test_ with my ROLE_BIOSECURITY_ADMIN account found:

Functioning:
- delete subscribers
- preview
- notify
- cannot access alerts-test.ala.org.au/admin, admin/user list, admin/user etc (correct)
- search with autocomplete
- download CSV (it is a blank csv for now, but I am authorised to download it, and ti works) 
- can download files using new "csv auditing" button

Not functioning:
- Delete an alert appears to work. But when the page is reloaded, the alert remains (screenshot below)
![Screenshot 2024-07-22 at 7 48 46 pm](https://github.com/user-attachments/assets/2d3dd8ab-984c-41da-a2ac-f020e8d4a658)

**Comment by kylie-m** [comment]
Delete an alert is now working well for a ROLE_BIOSECURITY_ADMIN on test. Thanks @qifeng-bai !
