### ISSUE TITLE
Metadata missing from Alerts reporting CSV

### ISSUE THREAD

**Issue by turley85** [AtlasOfLivingAustralia/alerts#238]
[collated_alerts_data-4.csv](https://github.com/user-attachments/files/16188179/collated_alerts_data-4.csv)

Additional fields need to be added to the alerts reporting CSV to be consistent with R alerts collated data report (attached)

**Comment by kylie-m** [comment]
This is the updated CSV requirement as discussed.

For background, see also previous ticket https://github.com/AtlasOfLivingAustralia/alerts/issues/191

**Comment by qifeng-bai** [comment]
Biocache does not contain all the values defined in this CSV., for example:

                    `search_term, lga,shape,list_name, cw_state,shape_feature, etc`

They are stored in Lists, not in Biocache

**Comment by qifeng-bai** [comment]
Work logs:
`https://api.ala.org.au/occurrences/occurrences/search?q=%28genus%3A%22Austropuccinia+psidii%22%29+OR+%28species%3A%22Austropuccinia+psidii%22%29+OR+%28subspecies%3A%22Austropuccinia+psidii%22%29+OR+%28scientificName%3A%22Austropuccinia+psidii%22%29+OR+%28raw_scientificName%3A%22Austropuccinia+psidii%22%29&fq=eventDate%3A%5B2024-02-01T13%3A00%3A00Z+TO+2024-07-26T06%3A18%3A54Z+%5D&fq=firstLoadedDate%3A%5B2024-06-30T14%3A00%3A00Z+TO+2024-07-26T06%3A18%3A54Z+%5D&pageSize=10000`

One of records, when we get this record via `https://biocache-ws.ala.org.au/ws/occurrences/d61bf447-2d6c-465f-bb9c-58277da5c090 `,  it has a list of 'cl', but not those info are not shown on the search url above

**Comment by kylie-m** [comment]
Hi Andrew, just bringing your slack question over here as it's closely related, it may or may not constitute a new requirement/request, depending on what you need:
"is there any report that could be sent at the end of each week or any errors that occur with alerts? Eg. anything I can review to troubleshoot any issues/errors from?"

The team is still working on the final reporting CSV, but as an intermediate step in their process, have produced these CSVs after alerts are sent: https://alerts-test.ala.org.au/biosecurity/csv. Perhaps this approach might already suit your needs?

I believe @qifeng-bai has some follow up questions on the reporting CSV requirements and will add those here soon, too

**Comment by turley85** [comment]
> https://alerts-test.ala.org.au/biosecurity/csv

Hi @kylie-m I can't access that link sorry. Can you either give access or send me an example?

**Comment by turley85** [comment]
<!DOCTYPE html>
head | where is the source from | how to use it | status | needed
-- | -- | -- | -- | --
state | cs_state ? stateProvince |   |   |  
match |   |   |   |  
search_term |   |   |   |  
correct_name |   |   |   |  
provided_name |   |   |   |  
common_name |   |   |   |  
lga |   |   |   |  
shape |   |   |   |  
cs_state |   |   |   |  
width |   |   |   |  
height

<br class="Apple-interchange-newline">

**Comment by turley85** [comment]
Follow our chat at stand up, I want to clarify key data requirements - we can probably simplify it a bit from what R alert CSV is. 

From Bai's list

State - Already included in the alert email - just the state or territory that it occurs in - Needed for filtering for reporting
LGA - To be included in alert email - the Local Government Authority that the alert occurs within - Needed for filtering for reporting - Can you use the LGA 2023 shapefile
search term - I don't know what this is? 
provided name - the raw scientific name that is used to match to the alert
correct name - that first name we highlight in the alert email (this could be the higher taxonomy name used in the email) that links to the Biocache record
common name - the common name we include in the alert email
shape - note sure this is needed if we just include the fq queries that were used for the alert
width - I don't know what this is - not needed
height - I don't know what this is - not needed

Other details, missing from Bai's list/csv but would be useful:
2. Occurrence link - to the occurrence record in the ALA - helpful for QA/QC
3. Occurence ID - link to the data sources as per biocache (eg https://biocache.ala.org.au/occurrences/e171ae84-819c-490e-ba0f-63587df912e9)
4. Identification verification status - as per biocache (use example above)

I hope that helps and let me know if you need any other info!

**Comment by kylie-m** [comment]
@turley85 as a workaround for access, could you try: 

1. access https://alerts-test.ala.org.au/admin/biosecurity 
2. complete login
3. then go to  https://alerts-test.ala.org.au/biosecurity/csv

**Comment by qifeng-bai** [comment]
@turley85  You wrote: "LGA - To be included in alert email - the Local Government Authority that the alert occurs within - Needed for filtering for reporting - Can you use the LGA 2023 shapefile"

Need further instruction

**Comment by kylie-m** [comment]
@turley85 thanks for this, a couple of extra points for @qifeng-bai  and the team to clarify:
- Occurence ID should already be included as record_id
- cl code is currently a blocker for us but it does sound like LGA and state will cater to your reporting needs, could you just clarify that?

**Comment by kylie-m** [comment]
@turley85 work in progress, @qifeng-bai or I will reach out with any questions

**Comment by kylie-m** [comment]
hi @turley85 , Bai has made some updates, could you give this a try on test? https://alerts-test.ala.org.au/admin/biosecurity

**Comment by nickdos** [comment]
https://spatial.ala.org.au/ws/layers/view/more/psma_lga_2018

**Comment by turley85** [comment]
So, was just trying to check in test and the "download CSV" isn't loading for me. Is that what I was meant to be checking @kylie-m

**Comment by turley85** [comment]
Looking better @kylie-m! Still missing some of the fields requested above like LGA and link to source data.

**Comment by qifeng-bai** [comment]
@turley85  The layer for LGA has not been fully uploaded. That is why LGA is empty. 
What is the link to source data?  Can you show me an example?

**Comment by turley85** [comment]
![image](https://github.com/user-attachments/assets/0e42daa6-9a8c-4082-a5cf-bfe2f327f859)

Sorry, occurrence ID as per metadata here

**Comment by qifeng-bai** [comment]
@turley85 if you check the CSV generated on 15/8, the first and second columns are the occurrence id and link 

[2024-08-15_BioSecurity_alert_for_00-TEST-alerts-km-excl_species_and_constrain_LGA.csv](https://github.com/user-attachments/files/16633253/2024-08-15_BioSecurity_alert_for_00-TEST-alerts-km-excl_species_and_constrain_LGA.csv)

**Comment by kylie-m** [comment]
Hi @turley85, here is the latest CSV reporting file, please take a look when you have a sec and let us know if you have any feedback.

As per our meeting discussion:
- cl, width, and height have been removed
- lga uses 2018/19 layer [cl10923](https://spatial.ala.org.au/ws/layers/view/more/10923) (agreed until 2023 layer is functional/available in the system)
- link to list URL remains
 https://csiroau.sharepoint.com/:x:/r/sites/AtlasofLivingAustraliaTeams/Shared%20Documents/Teams/Systems/Work%20Package/Alerts/csv-reporting-template/BioSecurity_alert_for_csv_audit_test-2024-08-20%20(2).csv?d=wbb9973ed6bfa4c3ab7bb334677bda16c&csf=1&web=1&e=L8y7lj

**Comment by turley85** [comment]
Thanks @kylie-m. That is looking good, and LGA is exactly what I was hoping for. 

I notice we've still got a "shape" field that is empty. Was there data for this?  If not, Is it possible to change this to "fq" and include the fq query used to generate that alert? (Eg. pull it from the list?) This will help with QC checks.

**Comment by kylie-m** [comment]
Thanks Andrew, that's great news! I'm just checking with the team now re: shape/fq columns

**Comment by qifeng-bai** [comment]
@turley85 fq has been added to CSV

**Comment by kylie-m** [comment]
Hi @turley85, we've added the fq column now, if you're happy with this CSV, I'll continue on with full functional testing for our release 

https://csiroau.sharepoint.com/:x:/r/sites/AtlasofLivingAustraliaTeams/Shared%20Documents/Teams/Systems/Work%20Package/Alerts/csv-reporting-template/biosecurity_alerts%20(5).csv?d=w0b97369360a240679c2879bff0861a01&csf=1&web=1&e=ZeskSp

**Comment by turley85** [comment]
That looks good - happy to push this through to functional testing.
