### ISSUE TITLE
Maps in alert email too zoomed out

### ISSUE THREAD

**Issue by turley85** [AtlasOfLivingAustralia/alerts#239]
Would like the map in alerts email to be more zoomed in. 

Currently, the map adds little in addition to the written location to aid users triaging the alerts. 

R alerts has much better resolution in the maps as attached.

<img width="658" alt="image" src="https://github.com/user-attachments/assets/0b2a5166-22d6-45bc-9b4b-cb86ae4b3a60">

**Comment by qifeng-bai** [comment]
@turley85 Could you inform us which email client you are using, please, so that we can test the styling against it?

**Comment by kylie-m** [comment]
@turley85 is that on Outlook? 
@shandiya could you confirm the zoom level used in R alerts?

**Comment by turley85** [comment]
Viewed in Outlook via safari browser @qifeng-bai

**Comment by shandiya** [comment]
@kylie-m we've been using zoom level 12

**Comment by kylie-m** [comment]
Awesome thanks @shandiya, fyi @qifeng-bai

**Comment by qifeng-bai** [comment]
Will update Zoom Level to 12

**Comment by qifeng-bai** [comment]
And then we may have this:
![Screenshot 2024-07-22 at 2 40 33 pm](https://github.com/user-attachments/assets/8f614d90-2d69-428a-8bec-5b38ca1d29cb)

**Comment by turley85** [comment]
@qifeng-bai, that is likely ok (it's the zoom we've been using to date) as long as we also add LGA as per this request: https://github.com/AtlasOfLivingAustralia/alerts/issues/235
