### ISSUE TITLE
Alerts for annotations count != list

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/alerts#24]
Lee reported that an alerts email for new annotations on records reported "1 occurrence records have been annotated" but the table shows 18 records in the list.

See screenshot:

![inbox_ _csiro](https://cloud.githubusercontent.com/assets/532845/16933840/76282fa4-4d94-11e6-838f-c384d925efcc.png)

**Comment by adam-collins** [comment]
Moving to #182, specifically fixing record count and records included queries used.
