### ISSUE TITLE
Possible issue - Alerting on Genus when species is required

### ISSUE THREAD

**Issue by turley85** [AtlasOfLivingAustralia/alerts#245]
Hi Team, 

I've detected a possible issue where an alert has been triggered for a genus (Caulerpa), when the user has specified species (Caulerpa taxifolia). 

When checking the list, I see that both matched name and raw common name are Caulerpa. Are either of these causing the alert, or is something else going on with this?

Relevant List: https://lists.ala.org.au/speciesListItem/list/dr27347?q=&offset=80&max=10&sort=rawScientificName&order=asc

![image](https://github.com/user-attachments/assets/9a2dfb63-91b1-470c-85b4-1653d367171b)

**Comment by turley85** [comment]
FYI, I had a chat to Cam about this and he's suggested we chat to Simon Sherrin if we need help resolving.

**Comment by kylie-m** [comment]
Thanks for flagging Andrew, I'm looking into a solution for this for you

**Comment by kylie-m** [comment]
Hi Andrew, we’ve discussed this as a team and it looks like the correct behaviour is happening, so to explain with a little more background:

- ALA matches Caulerpa taxifolia to a higher taxa Caulerpa, implying that Caulerpa taxifolia is not in the ALA taxonomy, as we know. (We see this in (1) the species list by comparing the supplied name and matched name, (2) the occurrence record where the scientific name is the genus and the raw scientific name is as supplied and (3) the biosecurity alert should match "Caulerpa taxifolia", that is not in the ALA taxonomy

- The alert is matching the occurrence that was provided to the ALA with the name "Caulerpa taxifolia”. (Ie. on the alert email where it says “Supplied as: Caulerpa taxifolia”)

- So the alert is not actually triggered for a genus, but for the name "Caulerpa taxifolia"

I hope that is helpful and please let us know if you have any more questions on it we can help out with

**Comment by turley85** [comment]
Thanks, the issue then is that primary display name in the alert email is the matched name... 

Although the alert is technically correct, the current implementation maybe confusing.

**Comment by turley85** [comment]
Also, can I get confirmation as to whether or not name "Caulerpa taxifolia" would match to all variations of this name found under "Caulerpa", or only records that match exactly?

Example of variations of name below:
<img width="587" alt="image" src="https://github.com/user-attachments/assets/9a08b431-35e8-438f-8697-c403146eb0b8">

**Comment by adam-collins** [comment]
In response to the confirmation, I cannot confirm what those records are. In the future please provide links to records.

The matching for "Caulerpa taxifolia" is successful on the raw_scientificName. When constructing the biocache-service query to test this the result is https://biocache.ala.org.au/occurrences/search?q=raw_scientificName:%22Caulerpa%20taxifolia%22.  You can use this to confirm what is or is not matched for this specific raw_scientificName search.

**Comment by turley85** [comment]
Thanks @adam-collins, this confirms we do have an issue as our alert for "Caulerpa taxifolia" would only alert on half the records in the ALA.

**Comment by turley85** [comment]
Followed up with taxonomy wg. They are aware of issue and working on it. I think this issue can be resolved now. 

Peggy
  10:30 AM
I see the problem: https://namematching-ws.ala.org.au/api/search?q=Pseudococcus%20longispinus I believe this is a known issue in namematching and we're working on a release in the coming months.
