### ISSUE TITLE
Search function in alert tool not working well

### ISSUE THREAD

**Issue by turley85** [AtlasOfLivingAustralia/alerts#247]
The current "Search by Query Name" in the alerts tool is difficult to use and maybe not working properly. 

I'd like to be able to search for an alert based on a part of the name. eg. using just ACPPO for the AUS_ACPPO_list alert. This currently isn't possible. 

I've also noticed that when typing an alert in the search bar, it displays a subset of alerts in the drop down. However, if the alert is not in that list (but is a real alert), it can't find it. Eg. typing "BioSecurity alert for AUS_ACPPO_list" did not find a result, even though this is the exact name of an alert.

**Comment by qifeng-bai** [comment]
Alerts only provides a limited full text search ability.  The keyword has to be a whole world

**Comment by turley85** [comment]
Could this please be improved, as at the moment it is not functional for searching in reality.

**Comment by qifeng-bai** [comment]
@turley85  Precisely, this is not a 'search' function; it is an 'auto-complete' function. I will log the 'search' requirement.

**Comment by kylie-m** [comment]
This is working really nicely for me on test, thanks Bai. @turley85 would you also like to give it a quick try and see what you think

**Comment by turley85** [comment]
Thanks @qifeng-bai, search looks to be working well in test :D
