### ISSUE TITLE
annotation alerts not triggering

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/alerts#26]
due to changes in the annotations functionality user_assertions:"true" is not longer in the index

2 things - 
modify creation of alerts on annotations to allow for this - new categories:
-unconfirmed (this is the initial assertion, of interest to data set curators)
-verified (checked by owner and record is correct)
-corrected (checked by owner and record has been fixed)
(all of the above?)

modify existing alerts to allow for this - edit existing alerts to trigger on any alerts status

**Comment by nickdos** [comment]
The underlying issue is that our search API has changed and thus previous searches with the old API (field or values) not longer work. We could fix this for assertions with a one-off modification of the alerts database but this will likely happen again in the future (and has already happened with other fields as well).

The non-technical fix is to tell people to remove the old alert and then re-run the search and create a new alert for the query.

**Comment by patkyn** [comment]
Need to update existing query that has been already been setup for annotation triggers for existing annotation to work. 

``` 
-- safe update. This updates query path containing both q=user_assertions:true and/or fq=user_assertions:true to the 3 new statuses Unconfirmed, Verified or Corrected

UPDATE alerts.query 
SET query_path = REPLACE (query.query_path, 'q=user_assertions:true', 'q=(user_assertions:50005%20OR%20user_assertions:50003%20OR%20user_assertions:50002)') 
WHERE instr(query.query_path, 'q=user_assertions:true') 
AND query.id > 0;


UPDATE alerts.query 
SET query_path_forui = REPLACE (query.query_path_forui, 'q=user_assertions:true', 'q=(user_assertions:50005%20OR%20user_assertions:50003%20OR%20user_assertions:50002)') 
WHERE instr(query.query_path_forui, 'q=user_assertions:true') 
AND query.id > 0;

```

**Comment by nickdos** [comment]
Just did the follwoing SQL in prod:
```
UPDATE query SET query_path = REPLACE(query_path, 'user_assertions:true','user_assertions:*');
UPDATE query SET query_path_forui = REPLACE(query_path_forui, 'user_assertions:true','user_assertions:*');
```

Looks OK so far.

**Comment by nickdos** [comment]
Annotation alerts are now coming through.
