### ISSUE TITLE
Getting alert I'm not subscribed to?

### ISSUE THREAD

**Issue by turley85** [AtlasOfLivingAustralia/alerts#262]

**Comment by turley85** [comment]
I've received an alert from this list in test: https://lists-test.ala.org.au/speciesListItem/list/dr22407

Which (as far as I can see) I'm not subscribed to. 

![image](https://github.com/user-attachments/assets/25acf422-5d41-4d83-9193-bb7d76a5a3f3)

**Comment by turley85** [comment]
![image](https://github.com/user-attachments/assets/582ec3da-a088-44ac-a148-c5125d11c932)

**Comment by kylie-m** [comment]
I'll do some more testing to narrow down what might be going on, fyi @qifeng-bai

**Comment by kylie-m** [comment]
Hi @turley85 , following up on this one, have you received any scheduled alerts for it, from test (ie same dr #) since?

**Comment by turley85** [comment]
No, this one seems to be resolved now. I didn't get any alerts for that list last week, when there was an occurrence.
