### ISSUE TITLE
Rewording Biosecurity reporting page, add csv deletion function etc

### ISSUE THREAD

**Issue by kylie-m** [AtlasOfLivingAustralia/alerts#265]
- Rewording of the downloads
- Hide the other downloads
- Make both prod + test to have the same behaviour around email notification
- Optional: Debugging - Include userId, ([logger.info](http://logger.info/)("userID - Trigger a Biosecurity email notification"+ listId))
- Combine all csv in to one global csv
- Test release - Thursday 22nd

----------------------------------
Added by @qifeng-bai 
- add admin or biosecurity admin link to my annotation page depending on the user roles
- add csv delete(rename .csv to .deleted, and those files won't be seen and aggregated ) button

**Comment by qifeng-bai** [comment]
See inlines
> * Rewording of the downloads
**Done**
> * Hide the other downloads
**Done**
> * Make both prod + test to have the same behaviour around email notification
**Done**
> * Optional: Debugging - Include userId, ([logger.info](http://logger.info/)("userID - Trigger a Biosecurity email notification"+ listId))

```
        We can find logs like below:
        log.info("****** Scheduled biosecurity update ****** " + new Date())
        biosecurityService.biosecurityAlerts()
        log.info("****** Scheduled biosecurity update finished ******" + new Date())

        However, it requires  more code changes and tests if we want to log who triggers the alerts
```

> * Combine all csv in to one global csv
> * Test release - Thursday 22nd

**Comment by kylie-m** [comment]
Thanks Bai, wording for the reporting page:

Title: 
Biosecurity Alerts Reporting


H2: 
All Biosecurity Alerts Data

Button text: 
Download Full CSV Report


Blurb: 
Download a comprehensive CSV file detailing all occurrence records from every biosecurity alert sent. This includes both scheduled and manual sends.



H2: 
Individual Biosecurity Alerts Data 

Blurb: 
Download individual CSV files for each biosecurity alert email, detailing all occurrence records. Files are sorted by the date the alert was sent.

**Comment by qifeng-bai** [comment]
Added

**Comment by kylie-m** [comment]
Thanks Bai, looks good!

**Comment by kylie-m** [comment]
@qifeng-bai Testing pass:

* CSV Reporting page - looks good, pass
* All alerts data CSV, incl fq column - pass
* Individual alert CSV downloads - pass
* CSV list - 'delete function' - pass

All of the above pass for both Admin and Biosecurity_Admin

* Admin button on My Alerts - pass
* Biosecurity Admin button on My Alerts - pass
