### ISSUE TITLE
Exclude data provider from alerts?

### ISSUE THREAD

**Issue by turley85** [AtlasOfLivingAustralia/alerts#269]
Some users may not want alerts from all data sources. 

For example, NSW may not wish to receive alerts from the NSW Biosecurity Information System (as they provided the data in the first place). 

Would it be possible to create an fq query to exclude data from particular datasets, similar to the  -taxon_name:"Osphranter rufus" query?

**Comment by turley85** [comment]
Eg. I'd like to exclude this dataset https://collections.ala.org.au/public/showDataResource/dr27665

https://lists.ala.org.au/speciesListItem/list/dr27362

**Comment by turley85** [comment]
Just confirming, I checked with the NSW alert list owner and they did say they'd like that dataset excluded.

**Comment by kylie-m** [comment]
Hi Andrew, for this one, try using `-data_resource_uid:"dr27665"` in your fq statement.

I have tested it with this test list (https://lists.ala.org.au/speciesListItem/list/dr28047) and it seems to be function ok using the following style of fq:
`-data_resource_uid:"dr27665" AND cl927:"New South Wales (including Coastal Waters)"`

**Comment by turley85** [comment]
Confirming that the -data_resource_uid:"dr27665" appears to be working. We'll just need to update the documentation with this. Thanks everyone!

**Comment by kylie-m** [comment]
Thanks Andrew, I can see you've added to the documentation, I'll close this issue off now
