### ISSUE TITLE
Alerts for new species list does not work properly

### ISSUE THREAD

**Issue by qifeng-bai** [AtlasOfLivingAustralia/alerts#270]
Alerts prod is using:

`https://collections.ala.org.au/ws/dataResource?resourceType=species-list`

to collect all available lists

In Alerts-test

We use `https://lists-test.ala.org.au//ws/speciesList?max=___MAX___&offset=___OFFSET___
`
This query supports sort=dateCreated&order=desc, but those parameters for sorting and ordering are missing in our query

 @adam-collins  mentioned that the queries on Prod is the point of the truth. We should use collection server

When we defined the properties of species list alerts as:

```
name: species_list_count, path: $.lists, fireWhenNotZero: false, fireWhenChange: true
 the value will be store into  species_list_count. [defined by name]
```

Here is an example:
`Current Value: dr22450   Previous Value: dr22450`

When 'fireWhenChange' is true,  the alerts will compare the first id it retrieves from list server with the id from the previous records , and return true if they are different.  

However, since those two query do not have 'sort' defined, they won't guarantee  the id of the first record is the new added one. 

**Alternative**
**It has been tested and passed on Alerts-test**
And 
Alerts for Blog use this solution already. Link: #256

 Change fireWhenChange and fireWhenNotZero both to false, it will force the Alerts to do a full comparison on current and previous records. By this way, we do not need to worry about sorting.

 `name: species_list_count, path: $.lists, fireWhenNotZero: false, fireWhenChange: false`

**Explanations about those two properties:**

```
fireWhenChange, indicates we should check if the last/first id has been changed
fireWhenNotZero, indicates we should check the number of records > 0

In this case, if name is species_list_count, fireWhenNotZero should be true, not fireWhenChange
```
**Check code**:
https://github.com/AtlasOfLivingAustralia/alerts/blob/develop/grails-app/services/au/org/ala/alerts/NotificationService.groovy#L323

**Comment by qifeng-bai** [comment]
Had this solution tested on Alerts-test

You can go to : https://alerts-test.ala.org.au/admin/query,  click-> specieslist tab -> find 'hourly subscribler'

You should see: ` name: species_list_count, path: $.lists, fireWhenNotZero: false, fireWhenChange: false`
Both are false. 

When you click 'dry run', or click 'https://alerts-test.ala.org.au/admin/dryRunQuery?queryId=9&frequency=hourly'
It would show the new added list

You can update the property with:  

```
#queryId can be found on that page as well

mysql> select * from property_path where query_id=9;
mysql> update alerts.property_path set fire_when_change = false where query_id=9;
```

**Comment by qifeng-bai** [comment]
After we added "charset=UTF-8" into the header:
<%@ page contentType="text/html; charset=UTF-8" %>

The preview page works well, but the email was added  a header: 
Content-Transfer-Encoding: quoted-printable

Which lets email show plain html/text.

On test server:
Without "charset=UTF-8",  "'" is not displayed properly on blog content, but it is displayed properly on title. 
 
However, both works will on my dev

**Comment by qifeng-bai** [comment]
Set fireWhenNotZero and fireWhenChange both to false. Wait for test

You can update using this SQL query:
`update alerts.property_path set fire_when_change = false where query_id=556;`

**Comment by kylie-m** [comment]
appears to be working now on both tests and production – new species list hourly emails are being received

**Comment by kylie-m** [comment]
re-testing on test for hourly and daily

**Comment by kylie-m** [comment]
hourly alert on test has been received, working well

**Comment by kylie-m** [comment]
scheduled daily alert on test received this morning, email template/links etc also working well
