### ISSUE TITLE
Last checked date and time not updating correctly

### ISSUE THREAD

**Issue by kylie-m** [AtlasOfLivingAustralia/alerts#273]
During full functional testing:
- the email alert was not triggered when clicking "Notify"
- the 'Last checked' date and time displayed for the alert (when notify was clicked)was not correctly updating

After discussion amongst the team:
- We believe it's due to expired auth
- Workaround for users: refresh page, sign in again, try again
- Issue seems relatively minor given the workaround 

Example of 'last checked' before triggering email with "Notify" button, and when error occurs and 'last checked' is not updated
![Screenshot 2024-09-03 at 5 26 58 pm](https://github.com/user-attachments/assets/b77e468f-f225-4275-a720-24f4bc4ca3f5)

When working: example of updated 'last checked', before refreshing page
![Screenshot 2024-09-03 at 5 27 05 pm](https://github.com/user-attachments/assets/f49d5b79-c2d4-4900-bb45-d9dbfd9d865f)

When working:  example of updated 'last checked', after refreshing page
![Screenshot 2024-09-03 at 5 27 15 pm](https://github.com/user-attachments/assets/4c2211be-a2d9-4df8-ae3d-5af7c7b1323f)

**Comment by qifeng-bai** [comment]
I have added some code in the Ajax client to handle errors, but it seems not to capture all types of errors.

Check code here:
https://github.com/AtlasOfLivingAustralia/alerts/blob/develop/grails-app/views/admin/biosecurity.gsp#L79

**Comment by kylie-m** [comment]
to do: test after auth has expired

**Comment by kylie-m** [comment]
Tested this morning after leaving overnight. No error msg isdisplayed, but page appears inactive:

1. select a date and click Notify on an alert
2. After clicking Notify, the usual message appears (below)
<img width="472" alt="Screenshot 2024-09-04 at 8 36 54 am" src="https://github.com/user-attachments/assets/4eb9fde4-697e-49e6-b16b-0a6fb12083df">

3. Noting seems to happen on the page, no new error msg is shown. 
4. Refreshing the page will prompt sign-in

- Doesn't appear to be a major issue / can workaround and let our internal users know to be aware of this
