### ISSUE TITLE
Email rendering issues

### ISSUE THREAD

**Issue by turley85** [AtlasOfLivingAustralia/alerts#280]
I've identified a couple of issue with alert email rendering. 

1. When forwarding an alert email, the alert get scrambled:
![thumbnail_image002](https://github.com/user-attachments/assets/667d512d-bf87-4f69-8d85-9ab515d64abf)

2. When Erin opens the alert emails in Outlook App the images are missing, and colours prevent reading. 
![image (4)](https://github.com/user-attachments/assets/d6d858d3-35ed-41ed-9940-fbd104e5dde0)

Erin reported that it looks OK when viewed in the Web, but not in outlook on the desktop app.

**Comment by nickdos** [comment]
After a few iterations of modifying the HTML template and checking with Erin, its now at an acceptable level of quality I think (not exactly the same as modern browser but close enough. Also, forwarding emails is now at this same "acceptable" level. See email forwarded from Erin, which is pretty close to what she sees in Outlook in Windows:

![image](https://github.com/user-attachments/assets/81ceda0a-78ee-41f1-bae3-20df5e806623)

**Comment by kylie-m** [comment]
Agree it's looking very acceptable to me too, when forwarded - on Outlook and Gmail, desktop and Mobile (iPhone)
screenshots included below:
![Screenshot 2024-09-16 at 12 48 33 pm](https://github.com/user-attachments/assets/da284a5a-ad62-412a-a164-fd607ffe9f24)
![Screenshot 2024-09-16 at 12 48 42 pm](https://github.com/user-attachments/assets/2d4ed22c-374a-442d-9fa7-9c1d7ee737da)
![Screenshot 2024-09-16 at 1 07 15 pm](https://github.com/user-attachments/assets/8cdf37a3-4584-4ffe-aee5-f9995c29ad8b)
![Screenshot 2024-09-16 at 1 07 25 pm](https://github.com/user-attachments/assets/5b5e9ccf-4bbe-4dee-9e23-07b345f8e2f7)
