### ISSUE TITLE
Rendering of images in alerts email

### ISSUE THREAD

**Issue by turley85** [AtlasOfLivingAustralia/alerts#288]
I was just forwarded a screenshot of the alert from one of our external uses. 

It appears the images are rendering at an odd size. Could we look into how to make the thumbnails the correct size?

![image](https://github.com/user-attachments/assets/86ba5b38-c332-486a-a315-ffd75d0904ad)

**Comment by turley85** [comment]
Just confirming Mark is using outlook app, not sure what version though.

**Comment by nickdos** [comment]
This seems to be the fix: https://stackoverflow.com/a/20990036/249327.

**Comment by nickdos** [comment]
Tested on Outlook with changes deployed to alerts-test.

![image](https://github.com/user-attachments/assets/42b30527-ff7b-49c5-854c-e8b183f7a854)
![image](https://github.com/user-attachments/assets/eb7bb91f-219c-496a-a426-332fe331c5ad)

**Comment by kylie-m** [comment]
Thanks Nick! They're looking all ok for me now on Mac for:
Outlook
Gmail - Chrome
Yahoo mail - Chrome

iOS:
Outlook
Gmail

The 'no image available' ratio appears a little compressed but overall the images are all the correct size
