### ISSUE TITLE
Kingdom not displaying correctly in Alerts CSV

### ISSUE THREAD

**Issue by turley85** [AtlasOfLivingAustralia/alerts#298]
[BioSecurity_alert_for_MarineCombinedList-2024-10-01.csv](https://github.com/user-attachments/files/17199835/BioSecurity_alert_for_MarineCombinedList-2024-10-01.csv)

In attached CSV download from alerts, Undaria sp. is being displayed as from the kingdom Kukiwakame, when it should be Chromista as per BIE.

**Comment by nickdos** [comment]
CSV row in question:

| recordID | recordLink | scientificName | taxonConceptID | decimalLatitude | decimalLongitude | eventDate | occurrenceStatus | dataResourceName | multimedia | mediaId | vernacularName | taxonConceptID_new | kingdom | phylum | class | order | family | genus | species | subspecies | firstLoadedDate | basisOfRecord | match | searchTerm | correct name | provided name | common name | state | lga layer | lga | fq | list id | list name | listLink | cw_state | shape feature | creator | license | mimetype | image url | date sent |   |   |   |  |
| -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- |
| 0736ea3e-be4a-4510-8d38-c83bef711209 | https://biocache.ala.org.au/occurrences/0736ea3e-be4a-4510-8d38-c83bef711209 | Undaria pinnatifida | NZOR-6-54356 | -37.865761 | 144.909668 | 22/09/2024 12:45:47 |   | iNaturalist Australia | Image | d24ee788-3b63-4952-b9e7-d04e1c04a8ad | Wakame [frond] | Mekabu [sporophyll] | Kukiwakame [midrib] |   | Chromista | Ochrophyta | Phaeophyceae | Laminariales | Alariaceae | Undaria | Undaria pinnatifida |   | 2024-09-23T00:38:28.058Z | HUMAN_OBSERVATION |   |   | Undaria pinnatifida | Undaria pinnatifida | Wakame [frond] | Mekabu [sporophyll] | Kukiwakame [midrib] | Victoria | LGA2023 |   | cl927:"Victoria (including Coastal Waters)" | dr28110 | BioSecurity alert for MarineCombinedList | https://lists.ala.org.au/speciesListItem/list/dr28110 |   |   | kerichater | CC-BY-NC 4.0 (Int) |   | https://images.ala.org.au/image/proxyImageThumbnail?imageId=d24ee788-3b63-4952-b9e7-d04e1c04a8ad | 01/10/2024 |

[Occurrence record](https://biocache.ala.org.au/occurrences/0736ea3e-be4a-4510-8d38-c83bef711209) shows:

Scientific name | Undaria pinnatifida
-- | --
Identified to rank | species
Common name | Wakame [frond], Mekabu [sporophyll], Kukiwakame [midrib]
Kingdom | Chromista
Phylum | Ochrophyta
Class | Phaeophyceae
Order | Laminariales
Family | Alariaceae
Genus | Undaria
Species | Undaria pinnatifida
Name match metric | exactMatch
Scientific name authorship | (Harv.) Suringar
Name parse type | SCIENTIFIC

Looks like a field offset bug when creating the CSV.
