### ISSUE TITLE
Blogs and news emails have broken unsubscribe message.

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/alerts#30]
At the bottom of the email is the text:

> To stop receiving alerts for Blogs and News, click here. To stop receiving all Atlas of Living Australia alerts, click here.

But "click here" link is buggered - applewebdata://2D079B1C-2A23-402B-ABEC-0F060C1011A6/[:][:]/unsubscribe?token=null

Issue is probably empty Map bits `[:]` indicating missing or incorrect config vars.

**Comment by nickdos** [comment]
Raw link is `<a href="[:][:]/unsubscribe?token=3D44164fed-7032-43ea-b199-a405eb475a89">`.

**Comment by nickdos** [comment]
Fixed in local deployment:

![dev_ala_org_au_8080_alerts_admin_debugalertemail_48_frequency_hourly_and_emailservice_groovy_-_alerts_-____documents_ala-code_alerts_](https://user-images.githubusercontent.com/532845/28763794-f67229a6-7603-11e7-9739-922e88c5f354.png)

mouse is hovering over last "click here" link

**Comment by nickdos** [comment]
This is mostly fixed now, but Blog alerts are still showing link with `token=null`

**Comment by nickdos** [comment]
Update: my emails now have a complete URL for the `To stop receiving all Atlas of Living Australia alerts, click here.` line but the previous line: `To stop receiving alerts for ALA Blog, click here.` still contains a broken URL, which is `https://alerts.ala.org.au/unsubscribe?token=null`.

I've tracked the issue down to this SQL statement: https://github.com/AtlasOfLivingAustralia/alerts/blob/ada516ceedc46f19e4dd30fd0b01eee7a27f1b8c/grails-app/services/au/org/ala/alerts/NotificationService.groovy#L426

Where the `Notification` table entry for the "ALA Blog" (ID:48) has an empty value for the column `unsubscribe_token`.

Issue appears to be that when this `Notification` entry was created, no UUID was populated for that field. Fix is to manually create one.

**Comment by nickdos** [comment]
The above commit may have fixed things, so monitoring for any bounce emails.

**Comment by ansell** [comment]
The email in ticket 23495 with a date of yesterday (Sunday 23 September) still has ``token=null`` for the full unsubscribe option.

**Comment by nickdos** [comment]
```
mysql> select count(*) from user where unsubscribe_token is null;
+----------+
| count(*) |
+----------+
|     2047 |
+----------+
1 row in set (0.00 sec)
```

so need the same fix I did for the notification table (sigh).

**Comment by ansell** [comment]
That would be the second part of this branch in the code:

https://github.com/AtlasOfLivingAustralia/alerts/blob/ada516ceedc46f19e4dd30fd0b01eee7a27f1b8c/grails-app/controllers/au/org/ala/alerts/UnsubscribeController.groovy#L58-L63

**Comment by nickdos** [comment]
I just created a new account and it got an `unsubscribe_token` set, so no longer a problem. Just need to fix 2047 broken accounts.

**Comment by nickdos** [comment]
Deployed and ran admin function - 2047 users fixed

![notification_service___atlas_of_living_australia](https://user-images.githubusercontent.com/532845/46190759-3041be80-c338-11e8-9930-ea210882437a.png)

**Comment by nickdos** [comment]
Fixed
