### ISSUE TITLE
Alerts for biocache searches with long queries fail.

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/alerts#39]
See https://support.ehelp.edu.au/helpdesk/tickets/23079

User was trying to get an alert for a species list (295 taxa) via the records link on the list page. See https://lists.ala.org.au/speciesListItem/list/dr8953. The records alerts resulted in an error "Request URI too long". Shortening the list to 50 taxa (https://lists.ala.org.au/speciesListItem/list/dr8954) seemed to work, as the alerts button forwarded onto "my alerts" page (expected behaviour) but the alert was not added to the list of custom alerts. So it appears to simply silently fail in this case.

**Comment by ansell** [comment]
Creating a QID and using it for the query is possibly a workaround (and is basically free in terms of storage, so you don't have to worry if you need to create a new one when they add a new species)

**Comment by Rita-C** [comment]
biocache-hub generates URL to create the alert, the `queryDisplayName` is too long in this case:
[JS code](https://github.com/AtlasOfLivingAustralia/biocache-hubs/blob/68d60a3b80d1c55f0c5a90727445af63be5339af/grails-app/assets/javascripts/search.js#L490)
suggest to truncate `queryDisplayName` in biocache-hub.

**Comment by Rita-C** [comment]
Issue moved to [AtlasOfLivingAustralia/biocache-hubs #394](https://github.com/AtlasOfLivingAustralia/biocache-hubs/issues/394) via [**ZenHub**](https://www.zenhub.com/)
