### ISSUE TITLE
Alerts may be sending out unrelated records in notification emails

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/alerts#40]
Report from a user that alerts is sending unrelated records in notification emails.

Refs ticket 23821 in helpdesk

**Comment by nickdos** [comment]
Cause is missing SOLR field in queries being sent to alerts system.

E.g. alerts is using 

https://biocache.ala.org.au/ws/occurrences/search?q=http://id.biodiversity.org.au/node/apni/2898914&sort=first_loaded_date&dir=desc&pageSize=20&facets=basis_of_record

but should have `q=lsid:{rest_of_query}` - 
https://biocache.ala.org.au/ws/occurrences/search?q=lsid:http://id.biodiversity.org.au/node/apni/2898914&sort=first_loaded_date&dir=desc&pageSize=20&facets=basis_of_record

**Comment by nickdos** [comment]
`ala-bie` bugs have been fixed (not deployed yet) but historical alerts are still broken and thus requires some SQL magic to fix them.

**Comment by ansell** [comment]
That is a negative scope though, which doesn't really restrict the number of positive ``?q=`` matches in terms of ``http``/``urn``/anything else. Not having looked at the list of course, just familiar with the number of ways that bie/biocache URLs are oddly constructed. If it works locally, likely to work in production right? YOLO!

**Comment by nickdos** [comment]
I did a broad `SELECT` based on the `WHERE name like 'New records for Species%' ` and checked the counts for the final SQL `update` so it wasn't broader than I was expecting. Should be OK and at least a lot better than the 237 and 388 queries that were completely busted.

**Comment by nickdos** [comment]
Closing - re-open if still an issue on prod.
