### ISSUE TITLE
Improve wording for unsubscribe links

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/alerts#42]
A few issues need fixing/improving:
- Blogs email have 2 unsubscribe messages (duplicated info), so the one inside the grey box should be removed
- wording for unsubscribe is not "industry standard", in that it refers to "alerts" which is not clear to the user what that means (its an internal reference to this project). Reword to be consistnent with most other systems. E.g. 

> if you no longer wish to receive emails for ALA blogs, [unsubscribe](https://alerts.ala.org.au/unsubscribe?token=b24ef1a9-f9fb-4fbd-879b-5dd80290e736XXX).

- [x] Add a link directly to the user alerts page - https://alerts.ala.org.au/notification/myAlerts as well. 
> Manage all your ALA email subscriptions via your [ALA subscriptions page](https://alerts.ala.org.au/notification/myAlerts).

- [x] Change heading on landing page - currently is it **My email alert** (note the singular alert!). Change to something like **My email subscriptions**.

- [x] Remove the line in "occurrence record alerts" `To disable this alert or to manage your alerts, click here. Your current settings are to receive alerts daily.` as we already have unsubscribe links at the bottom of the email that do the same thing.

**Comment by matthewandrews** [comment]
This change was released on 23 Feb 2021.

**Comment by alexhuang091** [comment]
@nickdos has this been applied to all email templates or only blog alert? If not should I update all other templates accordingly?

**Comment by nickdos** [comment]
Just apply to biosecurity template for now. We do want to update all the templates but want to get this one done and deployed as a priority.
