### ISSUE TITLE
No trigger could be found for ala.postie.HourlyQueriesJob

### ISSUE THREAD

**Issue by reupost** [AtlasOfLivingAustralia/alerts#43]
We're using v. 1.4-SNAPSHOT. After manually triggering the hourly alerts job to run for testing purposes, it now won't allow this type of job to be scheduled. If you click on the 'Start job schedule' you get an error 'No trigger could be found for ala.postie.HourlyQueriesJob'. Does anyone have any ideas on resolving this? Thanks.

**Comment by adam-collins** [comment]
Need to test if this is still an issue.

**Comment by nickdos** [comment]
The `Start job scedule` option should not be "clickable" under normal server conditions, as it should be running by default (thus `Pause job schedule` should be the only option). In development mode, the sceduler is not started by default, so you have to manually start it. I think this issue arrises where the scheduler is not running and the hourly job is manually triggered. Then when you try to start the global scheduler, it errors. This is not the normal order of operation for the app. Seeing as no further reports of this have come in, I'm closing this issue.
