### ISSUE TITLE
Deleting user account in auth should delete the account in alerts

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/alerts#44]
I deleted my test account a while ago in `auth.ala.org.au` and recreated it. However, both the old and new ids still exist in `alerts.ala.org.au`.

Past (should have been deleted):

`https://alerts.ala.org.au/admin/user/28185`

Current:

`https://alerts.ala.org.au/admin/user/59296`

There may be an issue with a link between `auth.ala.org.au` and `alerts.ala.org.au` where deletions are not propagated.

**Comment by nickdos** [comment]
Alerts should be checking regularly for users which have been marked as locked = true and sets its own local copy to locked. If it has a user account that does not have a corresponding account in AUTH, it also sets the local account to locked.

There is an issue with the library Alerts is using to check accounts in AUTH, where it caches the responses from AUTH indefinitely. I tried to fix that in the most recent version of alerts (can't remember if I deployed that before the holidays or not). Fix is to restart tomcat in the short term and re-run the admin command "Update user emails with CAS" at https://alerts.ala.org.au/admin.

**Comment by ansell** [comment]
Is it possible to see if an account is currently `locked` using the alerts admin interface? E.g., is there something I am missing on `https://alerts.ala.org.au/admin/user/28185` that shows whether it is locked?

**Comment by nickdos** [comment]
> Is it possible to see if an account is currently `locked` using the alerts admin interface? E.g., is there something I am missing on `https://alerts.ala.org.au/admin/user/28185` that shows whether it is locked?

No - its not in admin interface - you need to use MySQL...

I just ran the "update user emails..." link and it reported "Updated 0 email addresses in system", so its been running OK in terms of syncing with AUTH.

**Comment by ansell** [comment]
Ok, will close this as not an issue and open a feature request for showing whether accounts are locked in the admin interface

**Comment by nickdos** [comment]
This is still an issue - code is not setting `locked = true` for users that are no longer in userDetails DB (regression bug?).

**Comment by nickdos** [comment]
No - issue was a user changed their email address, so will open new issue for that.
