### ISSUE TITLE
Create alert links fail the first time

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/alerts#48]
I've seen this from `collectory` and `regions` pages that create biocache alerts. Clicking in the "Create alert" link the first time results in an error page (400) but hitting the back button, reloading the calling page and clicking the link a second time, works.

![image](https://user-images.githubusercontent.com/532845/55773078-6ecbe900-5ad2-11e9-989d-38c2c0df5a15.png)

https://alerts.ala.org.au/webservice/createBiocacheNewRecordsAlert?webserviceQuery=&uiQuery=&queryDisplayName=Museums+Victoria+provider+for+OZCAM&baseUrlForWS=https%3A%2F%2Fbiocache.ala.org.au%2Fws&baseUrlForUI=https%3A%2F%2Fbiocache.ala.org.au&resourceName=Atlas

No output in `alerts.log` in tomcat log fir either.

**Comment by nickdos** [comment]
https://alerts.ala.org.au/webservice/createBiocacheNewRecordsAlert?webserviceQuery=/occurrences/search?q=data_resource_uid:dr342&uiQuery=/occurrences/search?q=data_resource_uid:dr342&queryDisplayName=Museums%20Victoria%20provider%20for%20OZCAM&baseUrlForWS=https://biocache.ala.org.au/ws&baseUrlForUI=https://biocache.ala.org.au&resourceName=Atlas gets truncated https://alerts.ala.org.au/webservice/createBiocacheNewRecordsAlert?webserviceQuery=&uiQuery=&queryDisplayName=Museums+Victoria+provider+for+OZCAM&baseUrlForWS=https%3A%2F%2Fbiocache.ala.org.au%2Fws&baseUrlForUI=https%3A%2F%2Fbiocache.ala.org.au&resourceName=Atlas by AUTH I'm presuming???

**Comment by nickdos** [comment]
The commit above did fix the issue. I also checked the `query` table in the alerts DB to confirm the values being saved from the encoded params were correctly unencoded when saved.

**Comment by Rita-C** [comment]
✅ Tested creating "Alert me about new records" and "Alert me about annotations" for [Australian Museum Arachnology Collection](https://collections.ala.org.au/public/show/co116) 

✅ Tested creating Alerts for [ACT](https://regions.ala.org.au/States%20and%20territories/AUSTRALIAN%2520CAPITAL%2520TERRITORY#group=ALL_SPECIES&subgroup=&guid=&from=1850&to=2020&tab=speciesTab&fq=)
