### ISSUE TITLE
Allow HTML entities in Blog emails

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/alerts#49]
Quite a few Blog emails have shown escaped HTML entities in their titles:

![image](https://user-images.githubusercontent.com/532845/58854434-b5a81a80-86e0-11e9-87b5-c11695661a71.png)

In this case a `&#8211;` which looks like a emdash or similar.

Fix is to output this text with the `${raw(variable)}` syntax.

**Comment by Rita-C** [comment]
Received email from alerts-test
![Screen Shot 2021-02-18 at 2 36 56 pm](https://user-images.githubusercontent.com/29115246/108301800-d7b83800-71f6-11eb-952e-bf897bcf5a0e.png)

**Comment by nickdos** [comment]
code reviewed ✅
