### ISSUE TITLE
User account with a changed email address is not being updated in alerts

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/alerts#51]
See #25 and #44.

Seems to be a regression bug as this was fixed with code but now not working as expected.

Admin function was run `Update user emails with CAS` and it reported `Updated 0 email addresses in system`. However one of the users had changed their email address and I checked it before and after via SQL:

```
mysql> select * from user where id = 1313;
+------+---------+----------------------+--------------+---------+--------------------------------------+--------+
| id   | version | email                | frequency_id | user_id | unsubscribe_token                    | locked |
+------+---------+----------------------+--------------+---------+--------------------------------------+--------+
| 1313 |       2 | Myles@XXXX.com       |           15 | 538     | 68a1a9d7-6f29-4a30-be71-XXXXXXXXXXXXX| NULL   |
+------+---------+----------------------+--------------+---------+--------------------------------------+--------+
1 row in set (0.00 sec)
```

I eventually had to manually update the address via SQL:

```
mysql> update user set email = 'birddXXX@XXXXom' where id = 1313;
Query OK, 1 row affected (0.00 sec)
Rows matched: 1  Changed: 1  Warnings: 0
```

**Comment by Rita-C** [comment]
Hi @nickdos ,
I updated my email address locally, run admin `Update user emails with CAS` function, email updated. This seems to be fixed.

**Comment by nickdos** [comment]
probably worth testing on test site - I'll give it a go.

**Comment by Rita-C** [comment]
@nickdos , how did you go with testing on Test?

**Comment by nickdos** [comment]
Works - changed my test email and it was reflected in alerts-test.
