### ISSUE TITLE
Normalization of alerts ws calls and bioacache service configuration

### ISSUE THREAD

**Issue by vjrj** [AtlasOfLivingAustralia/alerts#57]
After PR https://github.com/AtlasOfLivingAustralia/alerts/pull/52 we have to normalize the way the alerts `/ws/` is called and how biocache and biocache-service is configured.

For instance:
- regions: [ws call code](https://github.com/AtlasOfLivingAustralia/regions/blob/master/grails-app/services/au/org/ala/regions/MetadataService.groovy#L224), it uses biocache and biocache service urls (I have my doubts that this is working currently in ALA production because maybe should get some `/ws/ws/` url in the queries). After PR https://github.com/AtlasOfLivingAustralia/alerts/pull/52 this should work well.
- bie-plugin: [ws call code](https://github.com/AtlasOfLivingAustralia/bie-plugin/blob/master/grails-app/assets/javascripts/species.show.js#L81), it uses always bioache url for both params, so should be patched to do a call similar to regions and to use biocache-service url.
- biocache-hubs: [ws call code](https://github.com/AtlasOfLivingAustralia/biocache-hubs/blob/master/grails-app/assets/javascripts/search.js#L488), it uses bioache and biocache service var but removing the `/ws/`. IMO it should be patched like `bie-plugin`.

Other (dirty) option is to intercept the remote call and normalize the params matching `biocache` and `biocache-ws` urls but I'm not sure if this is possible if alerts is used in other hubs. 

I can help if someone suggest me witch path to follow. Thanks.

**Comment by nickdos** [comment]
Thanks @vjrj - I'll have a look over this old code and get back to you. I agree in principle they should all work the same way but will need to check to see if there might be any reasons they are different.

**Comment by vjrj** [comment]
Other option is revert this PR, and make all LA portals except ALA to redirect calls like:

`https://biocache-ws.some-la.site/ws/` to `https://biocache-ws.some-la.site/`

**Comment by Rita-C** [comment]
Hi @vjrj ,
I created four alerts on my local from above apps, as

1. Regions,  alert when new records are added
2. Bie Receive alert when new records are added
3. Biocache get email alerts for new records 
4. Biocache get email alerts for new annotations

All have generated correct `urlString` starts as ` https://biocache.ala.org.au/ws/occurrences/search?q=lsid` in the Query.

**Comment by vjrj** [comment]
I'm not sure we are testing or using the same code. Let me try to describe a bit each module variables and calls.

About **alerts module**, `ala-install` alerts role has:
```
biocache.baseURL={{ biocache_url | default('https://biocache.ala.org.au/ws') }}
biocacheService.baseURL={{ biocache_service_url | default('https://biocache-ws.ala.org.au') }
```
But in [`application.yml`](https://github.com/AtlasOfLivingAustralia/alerts/blob/master/grails-app/conf/application.yml#L128)
```
biocache:
    baseURL: "https://biocache.ala.org.au"
biocacheService:
    baseURL: "https://biocache-ws.ala.org.au/ws"
```

In ALA inventories, only `biocache_url` is configured:
```
biocache_url = https://biocache.ala.org.au/ws
```

Would be nice that the default values in ala-install and application, although these variables are only used as default values when the API calls not provide the `baseUrlForWS`/`baseUrlForUI` values.

Let's see the **regions** module, the alerts calls are like:
```
baseUrlForWS    : URIUtil.encodeWithinQuery("${BIOCACHE_SERVICE_URL}")
baseUrlForUI    : URIUtil.encodeWithinQuery("${BIOCACHE_URL}"),
```
with:
```
BIOCACHE_URL = grailsApplication.config.biocache.baseURL
BIOCACHE_SERVICE_URL = grailsApplication.config.biocacheService.baseURL
```

In `ala-install` regions role, we have:
```
biocache.baseURL={{ biocache_base_url }}
biocacheService.baseURL={{ biocache_service_base_url }}
```

If ALA inventories looks like:
``` 
biocache_base_url=https://biocache.ala.org.au
biocache_service_base_url=https://biocache-ws.ala.org.au/ws
```

Our LA inventories looks like:
```
biocache_base_url = https://registros-es.l-a.site
biocache_service_base_url = https://registros-ws-es.l-a.site
``` 

And this should work in both cases.

Lets see the **bie-plugin**, the API calls are like:
```
url += "&baseUrlForWS=" + encodeURIComponent(SHOW_CONF.biocacheUrl);
url += "&baseUrlForUI=" + encodeURIComponent(SHOW_CONF.biocacheUrl);
```

In show.gsp:
```
<g:set var="biocacheUrl" value="${grailsApplication.config.biocache.baseURL}"/>
```

In ALA install `bie-hub` role:
```
biocache.baseURL={{ biocache_hub_url }}
```

So in ALA inventories:

```
biocache_hub_url = https://biocache.ala.org.au
```

In this case you cannot configure `biocache-ws.ala.org.au` for the webservice. And in this case I'm not sure the web service `query_path` are configured correctly in the db now that the `/ws` is not hardcoded.

In our LA inventories the two urls will looks like the biocache-hub url and in the case of LA inventories this does not works because we can have different subdomains and/or context path for `biocache-hub` and `biocache-service`.

The same happens with **biocache-hubs** module, the calls are like:
```
url += "&baseUrlForWS=" + encodeURIComponent(BC_CONF.biocacheServiceUrl.replace(/\/ws$/,""));
url += "&baseUrlForUI=" + encodeURIComponent(BC_CONF.serverName);
```

In home/index.gsp
```
<g:set var="biocacheServiceUrl" value="${grailsApplication.config.biocache.baseUrl}"/>
<g:set var="serverName" value="${grailsApplication.config.serverName ?: grailsApplication.config.biocache.baseUrl}"/>
```

In ala-install
```
serverName={{ biocache_hub_base_url }}
```

In ALA inventories:
```
biocache_hub_base_url = https://biocache.ala.org.au
```
That works right now but ALA cannot configure `biocache-ws.ala.org.au` and the `query_path` will not get the `/ws`.

In the case of LA inventories this does not works because we can have different subdomains and/or context path for `biocache-hub` and `biocache-service`.

So, for me the solution (especially for our LA portals) is to allow the configuration of `biocache-service` in both `bie-plugin` and `biocache-hubs` similar as `regions` do.

But, if works for you @Rita-C , probably I'm missing something.

Sorry for the extension.

**Comment by nickdos** [comment]
It appears the values in prod do not match the ansible vars...

![image](https://user-images.githubusercontent.com/532845/100018438-951dd400-2e30-11eb-9944-66433d6deef5.png)

**Comment by Rita-C** [comment]
Hi @vjrj , thanks for the clarification, it makes the scope much clearer now.
The variable names for `biocache` or `biocache-service` are very similar/confusing, I'll update the values to be consistent.

It seems the following urls return the same results:
`https://biocache-ws-test.ala.org.au/ws/occurrences/search?q=lsid:https://id.biodiversity.org.au/node/ausmoss/10102504&first_loaded_date%3A[2020-11-24T11%3A31%3A05Z%20TO%20*]&sort=first_loaded_date&dir=desc&pageSize=20&facets=basis_of_record`
`https://biocache-test.ala.org.au/ws/occurrences/search?q=lsid:https://id.biodiversity.org.au/node/ausmoss/10102504&first_loaded_date%3A[2020-11-24T11%3A31%3A05Z%20TO%20*]&sort=first_loaded_date&dir=desc&pageSize=20&facets=basis_of_record`, could be the reason `bie-plugin` and `biocache-hub` generated alerts worked.

**Comment by nickdos** [comment]
https://biocache-test.ala.org.au/ws is an alias for https://biocache-ws-test.ala.org.au/ws so they are the same service.

**Comment by Rita-C** [comment]
Hi @vjrj ,
Both `bie-plugin` and `biocache-hub` provide `ws/occurrences` as part of `webserviceQuery` as quoted in my above comment, hence `baseUrlForWS` does not require `ws` suffix.
```
        url += "&baseUrlForWS=" + encodeURIComponent(SHOW_CONF.biocacheUrl);
        url += "&baseUrlForUI=" + encodeURIComponent(SHOW_CONF.biocacheUrl);
        url += "&webserviceQuery=%2Fws%2Foccurrences%2Fsearch" + encodeURIComponent(searchString);
```

`webserviceQuery` is equivalent to `queryPath` in `BootStrap.groovy`, whose `ws` was removed in your change, 
```
        baseUrl: grailsApplication.config.biocacheService.baseURL,
        baseUrlForUI: grailsApplication.config.biocache.baseURL,
        description: descr,
        queryPath: '/occurrences/search?q=first_loaded_date:[___DATEPARAM___%20TO%20*]&sort=first_loaded_date&dir=desc&pageSize=20&facets=basis_of_record',
```
Doesn't the change make the approaches inconsistent? I may have missed something here?

**Comment by vjrj** [comment]
Thanks @Rita-C now I see the also the whole picture better also (I forget the hardcoded `/ws` calls).

To summarize a bit more, read this issue that explain how -minimally- affects to ALA this hardcoded `/ws` part in:
https://github.com/AtlasOfLivingAustralia/bie-plugin/issues/127

For us, the rest of LA portals that don't use biocache with `/ws` affects more. See this 404:
https://registros-ws.gbif.es/ws

Can I send some PR to both biocache and bie to try to make this more configurable without breaking things in ALA?

Thanks also @nickdos

**Comment by Rita-C** [comment]
Thanks @vjrj ,
We updated `ala-install` and `ALA inventories` to be consistent with your PR changes, also updated `biocache-hubs` and `bie-pluing`:
https://github.com/AtlasOfLivingAustralia/bie-plugin/issues/127
https://github.com/AtlasOfLivingAustralia/biocache-hubs/issues/387

To test:

1. Standard alerts, i.e. Annotation, new records, new images, Citizen science records with images
2. User created alert from biocache, new records, new annotation
3. User created alert from bie

**Comment by vjrj** [comment]
Thanks indeed @Rita-C the code looks good to me. I'll test in our side ASAP.

**Comment by vjrj** [comment]
I found time to test `bie-plugin`, and it works for us. Thanks indeed. I have to test `biocache-hubs`.

**Comment by vjrj** [comment]
I've tested upstream alerts, bie, ala-hub and regions and all works for me. Thanks indeed!

**Comment by Rita-C** [comment]
Thank you @vjrj .
Moving ticket to cab ready.
