### ISSUE TITLE
Biosecurity project - allow the option for an alert email to be sent even if no records trigger the alert

### ISSUE THREAD

**Issue by m-hope** [AtlasOfLivingAustralia/alerts#59]
Background: As per issue #58, the Biosecurity project is using the ALA Alert functionality to send notifications to DAWE of any potential new pest records appearing in the ALA.  As far as I am aware, the alert function will not send an alert email if no records appear in the alert query, however in this case, it would be beneficial to let DAWE know that the query has been checked even if no records trigger the alert, to confirm there is not an issue with the alert system.

**Comment by nickdos** [comment]
This will be a "medium" size task, as the current alerts architecture involved doing a `diff` against content stored for a given `query` with what it found the previous time it ran. When it finds a difference in the output, that triggers the email.

So for this to be changed, we'd need to add an extra flag to the data model for a query and then catch that when the diff returns `null` so we can still send an email.

**Comment by m-hope** [comment]
Thanks Nick, given the complexity for is a low priority task, I think we park this for the time being.

**Comment by m-hope** [comment]
Just as a side note:  it occurred to me that there have been quite a few instances in the past where the only indication the alert system is not working  is because the collection community managers have noticed that "they haven't seen an annotation alert for a couple of months"... I suspect they would be interested in this feature as well.

**Comment by Rita-C** [comment]
We will also require a change to the UI (e.g. `https://alerts-test.ala.org.au/notification/myAlerts`), allowing user to indicate if receiving email for no record check, should this option only apply to new record or all alerts?

**Comment by nickdos** [comment]
> We will also require a change to the UI (e.g. `https://alerts-test.ala.org.au/notification/myAlerts`), allowing user to indicate if receiving email for no record check, should this option only apply to new record or all alerts?

I think we can skip that for now - we only want a MVP so only needs to work like this for the biosecurity alerts, so all other alerts should not be affected.

**Comment by m-hope** [comment]
Agreed.

**Comment by Rita-C** [comment]
> the collection community managers have noticed that "they haven't seen an annotation alert for a couple of months".

Hi @m-hope, do the mangers expect annotation alerts from a specific collectory? There's some investigation going on at the moment about collectory permissions/roles. Tim who subscribed to the alert annotation for all datasets received alert emails recently.

**Comment by adam-collins** [comment]
Is this still required?
