### ISSUE TITLE
Region page alerts bug

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/alerts#62]
See https://alerts.ala.org.au/query/show/1151

`Base Url For UI   |    https://biocache.ala.org.au&resourceName=Atlas`

Should be `https://biocache.ala.org.au`.

**Comment by ansell** [comment]
I QA'd this on `regions-test.ala.org.au` creating the following alert `https://alerts-test.ala.org.au/query/show/10`
