### ISSUE TITLE
Searches with long display titles silently fail

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/alerts#65]
E.g. `qid` searches with very long titles seem to fail silently - no error but alerts page does not show the alert after trying to create it. 

E.g. https://biocache.ala.org.au/occurrences/search?q=qid:1603931265406

which has title:

`(raw_name:"Acarapis" OR raw_name:"Anentome" OR raw_name:"Astacus leptodactylus" OR raw_name:"Atelerix albiventris" OR raw_name:"Aulacaspis yasumatsui" OR raw_name:"Biomphalaria" OR raw_name:"Boa constrictor" OR raw_name:"Bombus impatiens" OR raw_name:"Bulinus" OR raw_name:"Calotes versicolor" OR raw_name:"Carex kobomugi" OR raw_name:"Chamaeleo calyptratus" OR raw_name:"Chelydra serpentina" OR raw_name:"Cipangopaludina" OR raw_name:"Clea" OR raw_name:"Coptotermes formosanus" OR raw_name:"Corvus splendens" OR raw_name:"Cristaria plicata" OR raw_name:"Cynops orientalis" OR raw_name:"Cytisus striatus" OR raw_name:"Delta pyriforme" OR raw_name:"Dichroplus" OR raw_name:"Dinophysis norvegica" OR raw_name:"Dreissena" OR raw_name:"Duttaphrynus melanostictus" OR raw_name:"Dysmicoccus neobrevipes" OR raw_name:"Eriocheir" OR raw_name:"Euglandina rosea" OR raw_name:"Glischrochilus" OR raw_name:"Halyomorpha halys" OR raw_name:"Harmonia axyridis" OR raw_name:"Hemidactylus platyurus" OR raw_name:"Hemigrapsus" OR raw_name:"Hemimysis anomala" OR raw_name:"Hypomeces squamosus" OR raw_name:"Iguana iguana" OR raw_name:"Incisitermes minor" OR raw_name:"Indoplanorbis exustus" OR raw_name:"Kaloula pulchra" OR raw_name:"Limnoperna fortunei" OR raw_name:"Ludwigia grandiflora" OR raw_name:"Lymantria dispar" OR raw_name:"Marenzelleria neglecta" OR raw_name:"Microstegium vimineum" OR raw_name:"Mnemiopsis leidyi" OR raw_name:"Mya arenaria" OR raw_name:"Oncomelania" OR raw_name:"Orconectes" OR raw_name:"Pacifastacus leniusculus" OR raw_name:"Pantherophis guttatus" OR raw_name:"Perna perna" OR raw_name:"Pomacea canaliculata" OR raw_name:"Pomacea maculata" OR raw_name:"Procambarus clarkii" OR raw_name:"Pyrgophorus platyrachis" OR raw_name:"Python bivittatus" OR raw_name:"Radix" OR raw_name:"Rapana venosa" OR raw_name:"Rhithropanopeus harrisi" OR raw_name:"Sargassum muticum" OR raw_name:"Senecio inaequidens" OR raw_name:"Seriphium plumosum" OR raw_name:"Tarebia granifera" OR raw_name:"Tibouchina herbacea" OR raw_name:"Tropilaelaps" OR raw_name:"Urosalpinx cinerea" OR raw_name:"Ventenata dubia" OR raw_name:"Vespa velutina")`

Checking alerts [`query` list](https://alerts.ala.org.au/query/list), shows this was not created.

**Comment by m-hope** [comment]
As a workaround for this, I had to break the queries up into individual chunks to get under a limit of what seemed to be around 250 characters for the entire URL (ie: including the https://biocache... etc).

As an aside, I found an issue in setting an alert when no records are found for a query. I've documented this in a separate issue ()

**Comment by Rita-C** [comment]
Code updated as discussed, @nickdos could you review the changes please?

**Comment by nickdos** [comment]
Code checked ✅
