### ISSUE TITLE
Ability to set query based alert when no records found

### ISSUE THREAD

**Issue by m-hope** [AtlasOfLivingAustralia/alerts#66]
When sorting out a workaround for issue #65, I found that if you are trying to set a query based alert where the query currently does not return any records, you don't get the "alert" button to set the query.  I don't know if there is an alternative way to do this, but it would be good to either still have the alert button on the "no records found" page, or let the user know what the alternate mechanism is if there is one.

Note: I did try attaching "#alertNewRecords" to the query (which seems to be how the alert button works), but it did not seem to do anything and the query/alert did not appear in the manage alerts page.

**Comment by Rita-C** [comment]
Hi @m-hope,
The alert buttons are generated in `biocache-hub`, I'm moving this ticket to `biocache-hub`.

**Comment by Rita-C** [comment]
Issue moved to [AtlasOfLivingAustralia/biocache-hubs #386](https://github.com/AtlasOfLivingAustralia/biocache-hubs/issues/386) via [**ZenHub**](https://www.zenhub.com/)

**Comment by m-hope** [comment]
Thanks @Rita-C
