### ISSUE TITLE
Alerts deletion from the admin section does not work

### ISSUE THREAD

**Issue by vjrj** [AtlasOfLivingAustralia/alerts#71]
The first reason is because the method `DELETE` is not allowed:
```
diff --git a/grails-app/controllers/au/org/ala/alerts/QueryController.groovy b/grails-app/controllers/au/org/ala/alerts/QueryController.groovy
index 82e491a..6e486d8 100644
--- a/grails-app/controllers/au/org/ala/alerts/QueryController.groovy
+++ b/grails-app/controllers/au/org/ala/alerts/QueryController.groovy
@@ -6,7 +6,7 @@ import org.springframework.dao.DataIntegrityViolationException
 
 class QueryController {
 
-    static allowedMethods = [save: "POST", update: "POST", update: "PUT", delete: "POST"]
+    static allowedMethods = [save: "POST", update: "POST", update: "PUT", delete: ["POST", "DELETE"]]
     def authService
 
     def index() {
``` 

But still after fix this, there are some sql foreign key issue:
```
org.springframework.dao.DataIntegrityViolationException: Hibernate operation: could not execute statement; SQL [n/a]; Cannot delete or update a parent row: a foreign key constraint fails (`alerts`.`notification`, CONSTRAINT `FKaw8acafm8nn6fg0b6x1e5gb90` FOREIGN KEY (`query_id`) REFERENCES `query` (`id`)); nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Cannot delete or update a parent row: a foreign key constraint fails (`alerts`.`notification`, CONSTRAINT `FKaw8acafm8nn6fg0b6x1e5gb90` FOREIGN KEY (`query_id`) REFERENCES `query` (`id`))
```

So some delete cascade should be done also.

**Comment by Rita-C** [comment]
Steps to test the issue: @vjrj please add anything that I missed

1. Create an alert from Biocache -> the alert displayed in your alert list page `https://alerts-test.ala.org.au/notification/myAlerts`
2. Go to alert admin, locate the alert on alert type page, open the alert -> the `Delete` button is not visible
3. Wait for scheduled job to complete -> check there are entries in `query_result`, `property_value` and `property_path` tables)
4. Delete the alert from your alert list page
5. Go to alert admin again, locate the alert on alert type page, open the alert -> the `Delete` button now is visible
6. Click `Delete` button -> the alert no longer shown on the alert type page

**Comment by Rita-C** [comment]
Moving this to "CAB Ready" as @vjrj has reviewed and tested the changes.
