### ISSUE TITLE
Incorrect querypath for annotation alerts

### ISSUE THREAD

**Issue by Rita-C** [AtlasOfLivingAustralia/alerts#73]
Notify me when annotations are made on any record, 
Query path `/occurrences/search?fq=user_assertions:*&q=last_assertion_date:[___DATEPARAM___%20TO%20*]&sort=last_assertion_date&dir=desc&pageSize=20&facets=basis_of_record` does not trigger an alert when annotation made against record.

**Comment by alexhuang091** [comment]
Hi Rita, I did a test on change. 

biocacheService.baseURL: "`https://biocache-ws-test.ala.org.au/ws`"
biocache.baseURL: "`https://biocache-test.ala.org.au`"

- the 1st time I ran it (via `admin/runChecksNow?frequency=weekly`) , there's no diff.
- the 2nd time, the returned json has 44 records. But you see records.size == 20 but totalRecords = 44
<img width="1372" alt="截屏2021-01-28 下午3 17 26" src="https://user-images.githubusercontent.com/61677987/106090038-4ae10800-617d-11eb-99f0-066cc1858872.png">

- then I flagged an issue and did a 3rd check. totalRecords = 45 which is correct, records.size == 20
<img width="1226" alt="截屏2021-01-28 下午3 23 58" src="https://user-images.githubusercontent.com/61677987/106090245-de1a3d80-617d-11eb-94c3-659ec45fa1ce.png">


But the thing is, should we only send the diff (45 - 44, the newly flagged) in the email to the users? Current code seems always send all records.

**Comment by Rita-C** [comment]
Thanks for testing @alexhuang091 
- Just checked my received email, only newly added records were included. 
```
    def getNewRecords(QueryResult queryResult) {

        //decompress both and compare lists
        if (queryResult.query.recordJsonPath) {
            String last = decompressZipped(queryResult.lastResult)
            if (last) {
                JsonPath.read(last, queryResult.query.recordJsonPath)
            } else {
                []
            }
        } else {
            []
        }
    }
```
- Maybe there are 20 new annotations? Try hours?

**Comment by alexhuang091** [comment]
> * Maybe there are 20 new annotations? Try hourly?

Hi Rita,

I did another round of test. This time the record number seems correct, but there's another issue.

1. clear database, launch the program, do a check via `admin/runChecksNow?frequency=hourly`, returned json has 1 record. no change.
2. run check again, change detected.
3. run check again without adding new annotaion, change detected.
4. keep checking chage without adding new annotation, change detected everytime.

I think the thing is, we have `new PropertyPath([name: "totalRecords", jsonPath: "totalRecords", query: newAssertions, fireWhenNotZero: true]).save()`

`fireWhenNotZero` means as long as the totalRecords in the checkresult !=0, we'll view it as changed.

Is this alert desgined to be like this? Shouldn't it only alert when NEW annotation is made?
