### ISSUE TITLE
Missing “New occurrence datasets” standard alert type

### ISSUE THREAD

**Issue by Rita-C** [AtlasOfLivingAustralia/alerts#78]
“New occurrence datasets”  is not checked at application start time. Add it back to BootStrap

**Comment by Rita-C** [comment]
Hi @vjrj ,
ALA Alerts prod has a Query “New occurrence datasets” which is not in `BootStrap.grrovy`. Does it exist in your instance? I’m adding it to `BootStrap.grrovy` wanted to know if I need to include a flag, e.g. 
```
if (grailsApplication.config.useCitizenScienceAlerts.toBoolean())
```

**Comment by vjrj** [comment]
This query exists and works in our prod instance by default. Do you want to make it conditional?

**Comment by Rita-C** [comment]
> This query exists and works in our prod instance by default. Do you want to make it conditional?

It sounds like no need to make it conditional, thanks @vjrj

**Comment by vjrj** [comment]
Ok, I see, maybe is a problem of the locale not correctly set or read. This line should be the problem:
https://github.com/AtlasOfLivingAustralia/alerts/blob/9f790789d22e05885ac3baab642f0f4252cdd319/grails-app/init/au/org/ala/alerts/BootStrap.groovy#L177
in our side we have all the queries in "Spanish". So it finds this translated title in the default queries. For some reason is not find your English query name.
![2021-11-21-23-31-26-screenshot](https://user-images.githubusercontent.com/180085/105420525-ce13d280-5c40-11eb-9e51-2c02619c32e1.png)

**Comment by vjrj** [comment]
In new deployments there are a default config variable `siteDefaultLanguage=en` can you verify this?

**Comment by vjrj** [comment]
Verify this setting: https://github.com/AtlasOfLivingAustralia/ala-install/blob/9472158968574fdf06c4c5e3d57f34b6415ac972/ansible/roles/alerts/templates/alerts-config.properties#L65

**Comment by Rita-C** [comment]
This is actually another dataset alert I'm adding - "new occurrence dataset"
<img width="396" alt="Screen Shot 2021-01-22 at 9 36 01 am" src="https://user-images.githubusercontent.com/29115246/105420992-73589600-5c95-11eb-81b6-6db76d0f3257.png">

**Comment by Rita-C** [comment]
What I found was this "new occurrence datasets" was not in the` BootStrap.groovy`. I'll check in the change and get you to take a look.

**Comment by Rita-C** [comment]
Hi @vjrj , code checked in as in above commit. Could you provide me i18n text for `messages_es.properties` please?

**Comment by vjrj** [comment]
Hi again @Rita-C your new query LGTM . From our side, I think that is perfect to add this query by default in `Bootstrap.groovy` without a flag. 

I added conditional statements only in some cases for portals without species lists, spatial or wp blog, ... but in this case, all LA portals have a collectory so it's safe to add it by default.

**Comment by Rita-C** [comment]
Thanks @vjrj
